-- Postos Descobertos — Produtividade
-- Origem: PBI "Posto Descoberto - Produtividade.pbix".
-- Cada linha = um PONTOVAGA (posto-vaga) NÃO coberto numa data, com o MotivoPV
-- (Posto Vago, Falta, Férias, Folga, Remanejamento, Suspensão, Reciclagem,
-- Saída Antecipada, Correção). Período via @DATA_INICIO / @DATA_FIM (parâmetros).
WITH RESULTADO AS (

 select distinct
	VAGAITEMCONTRATO.VAGAITEMCONTRATO,
	LOCALSERVICOEMP.EMPRESA AS COD_EMPRESA,
	ENTEMPRESA.NOMERESUMIDO AS DESCEMPRESA,
	LOCALSERVICO.BASEOPERACIONAL,
	ENTBASEOP.NOMERESUMIDO AS DESCBASEOPERACIONAL,
	PONTOVAGA.DATA,
	RELENTCLI.CODIGO AS COD_CLIENTE,
	ENTCLI.NOMERESUMIDO AS CLIENTE,
	RELLOCAL.CODIGO AS COD_LOCAL,
	ENTLOCAL.NOMERESUMIDO AS LOCALSERVICO,
	ENTPOSTO.NOMERESUMIDO AS POSTO,
	PONTOVAGA.VAGAITEMCONTRATO AS 'PONTOVAGA',
	TURNOTRABALHO.DESCRICAO AS DESCTURNO,
	CARGO.CARGO AS COD_CARGO,
	CARGO.DESCRICAO AS DESCCARGO,
	ESCALATRABALHO.ESCALATRABALHO AS COD_ESCALA,
	ESCALATRABALHO.DESCRICAO AS ESCALA,
	RELFUNC.CODIGO AS RE,
	ENTFUNC.NOMERESUMIDO AS NOMEFUNC,
	SITUACAOMOBRATEMP.SITUACAOMOBRA AS COD_SITUACAO,
	SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL AS SITUACAO,
	SITMOBRAHOJE.SITMOBRAHOJE AS COD_SITMOBRAHOJE,
	SITMOBRAHOJE.DESCRICAOAMIGAVEL AS SITUACAO_PONTO,
	LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO AS CODAREASUPERVISAO,
	ENTAREA.NOMECOMPLETO AS NOMEAREASUPERVISAO,
	RELSUP.CODIGO AS COD_GESTOR_OP,
	ENTSUP.NOMECOMPLETO AS NOME_GESTOR_OP,
	MOTMOVIMENTACAO.DESCRICAO AS MOTIVO_IMPLANTACAO,
	VAGAITEMCONTRATO.ORIGEMVAGA AS ORIGEMVAGA,
	CASE
		WHEN CONTRATO.TPMENSALEVENTO = 1 THEN 'MENSAL'
		WHEN CONTRATO.TPMENSALEVENTO = 2 THEN 'EVENTO'
		WHEN CONTRATO.TPMENSALEVENTO = 3 THEN 'EVENTO PRÉ-DETERMINADO'
		WHEN CONTRATO.TPMENSALEVENTO = 4 THEN 'MENSAL PRÉ-DETERMINADO'
	END AS TPMENSALEVENTO,
	PONTOVAGA.SITUACAOCOBERTA,
	case
		when PONTOVAGA.SITUACAOCOBERTA=0 then 'DESCOBERTA'
		when PONTOVAGA.SITUACAOCOBERTA=2 then 'BLOQUEADA'
		when PONTOVAGA.SITUACAOCOBERTA=3 then 'JUSTIFICADA'
	end DESCSITUACAOCOBERTA,
	CASE
		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. PAR. FUNC.'
			OR SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. PAR. CLI.' THEN 'Saida Antecipada'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'ATIVO' THEN 'Correção'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'INSS' THEN 'Falta'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'FÉRIAS' THEN 'Férias'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'RECICLAGEM' THEN 'Reciclagem'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'SUSPENSÃO' THEN 'Suspensão'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'FERIAS TRAB.' THEN 'Correção'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL IS NULL THEN 'Posto Vago'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. TOT. COB.'
			OR  SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. PAR. COB.'
			OR  SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'FOLGA CANCELADA'	THEN 'Remanejamento'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'FALTA'			THEN 'Falta'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. TOTAL'		THEN 'Folga'
	end as 'MotivoPV',
	PONTOVAGA.MOTVGDESCOBERTA AS COD_MOTIVO_DESCOBERTA,
	ITENSCONTRATO.DESCRICAOFISCAL,
	ENDERECOPOSTO.CEP CEP_POSTO,
	TPLOGRADOUROPOSTO.NOMETPLOGRADOURO TIPO_LOGRADOURO_POSTO,
	ENDERECOPOSTO.NOMELOGRADOURO LOGRADOURO_POSTO,
	ENDERECOPOSTO.NUMERO NUMERO_POSTO,
	ENDERECOPOSTO.COMPLEMENTO COMPLEMENTO_POSTO,
	ENDERECOPOSTO.NOMEBAIRRO BAIRRO_POSTO,
	ENDERECOPOSTO.SIGLAUF UF_POSTO,
	ENDERECOPOSTO.PONTOREFERENCIA PONTO_REFERENCIA_POSTO,
	LOCALIDADE.NOMELOCALIDADE CIDADE_POSTO
	from  LOCALSERVICOEMP
		inner join RELACAOENTIDADE RELEMPRESA on (RELEMPRESA.RELACAOENTIDADE=LOCALSERVICOEMP.EMPRESA)
		inner join ENTIDADE ENTEMPRESA on (ENTEMPRESA.ENTIDADE=RELEMPRESA.PAPEL1)
		inner join LOCALSERVICO on (LOCALSERVICO.LOCALSERVICO=LOCALSERVICOEMP.LOCALSERVICO)
		inner join RELACAOENTIDADE RELBASEOP ON (RELBASEOP.RELACAOENTIDADE=LOCALSERVICO.BASEOPERACIONAL)
		inner join ENTIDADE ENTBASEOP ON (ENTBASEOP.ENTIDADE=RELBASEOP.PAPEL1)
		inner join POSTOLOCALSERVICO on (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)
		inner join VAGAITEMCONTRATO on (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO and VAGAITEMCONTRATO.ORIGEMVAGA<>5)
		INNER JOIN CONTRATO ON CONTRATO.CONTRATO = VAGAITEMCONTRATO.CONTRATO
		inner join PONTOVAGA on (PONTOVAGA.VAGAITEMCONTRATOEFETIVO=VAGAITEMCONTRATO.VAGAITEMCONTRATO and PONTOVAGA.SITTRABALHO=1 and PONTOVAGA.SITUACAOCOBERTA<>1)
		inner join LIGAVGITEMCONTRATO on (VAGAITEMCONTRATO.VAGAITEMCONTRATO=LIGAVGITEMCONTRATO.VAGAITEMCONTRATO
													and LIGAVGITEMCONTRATO.DTIMPLANTACAO<=PONTOVAGA.DATA
													and ((LIGAVGITEMCONTRATO.DTENCERRAMENTO is null)
													or (LIGAVGITEMCONTRATO.DTENCERRAMENTO>=PONTOVAGA.data)))
		inner join COMPOSICAOITENSCONTRATO on (LIGAVGITEMCONTRATO.COMPOSICAOITENSCONTRATO=COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO)
		inner join ITENSCONTRATO on (COMPOSICAOITENSCONTRATO.ITENSCONTRATO=ITENSCONTRATO.ITENSCONTRATO)
		inner join TURNOTRABALHO on (TURNOTRABALHO.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO)
		inner join CARGO on (CARGO.CARGO=VAGAITEMCONTRATO.CARGO)
		inner join RELACAOENTIDADE RELLOCAL on (RELLOCAL.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)
		inner join ENTIDADE ENTLOCAL on (ENTLOCAL.ENTIDADE=RELLOCAL.PAPEL1)
		inner join RELACAOENTIDADE RELENTCLI on (RELENTCLI.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)
		inner join CLIENTE on (CLIENTE.CLIENTE=VAGAITEMCONTRATO.CLIENTE AND (CLIENTE.TIPOCLIENTE=1 or VAGAITEMCONTRATO.ORIGEMVAGA=10))
		inner join ENTIDADE ENTCLI on (ENTCLI.ENTIDADE=RELENTCLI.PAPEL1)
		inner join RELACAOENTIDADE RELPOSTO on (RELPOSTO.RELACAOENTIDADE=POSTOLOCALSERVICO.POSTOSERVICO)
		inner join ENTIDADE ENTPOSTO on (ENTPOSTO.ENTIDADE=RELPOSTO.PAPEL1)
		inner join ESCALATRABALHO on (ESCALATRABALHO.ESCALATRABALHO=VAGAITEMCONTRATO.ESCALATRABALHO)
		left join ALOCACAOMAODEOBRA
		INNER JOIN MOTMOVIMENTACAO	ON (MOTMOVIMENTACAO.MOTMOVIMENTACAO=ALOCACAOMAODEOBRA.MOTIVOIMPLANTACAO)
									on (ALOCACAOMAODEOBRA.VAGAITEMCONTRATO=PONTOVAGA.VAGAITEMCONTRATO
										and ALOCACAOMAODEOBRA.SITALOCACAO=1
										and ALOCACAOMAODEOBRA.DTINICIO<=PONTOVAGA.DATA
										AND (ALOCACAOMAODEOBRA.DTFIM IS NULL OR ALOCACAOMAODEOBRA.DTFIM>=PONTOVAGA.DATA))
		left join PONTO
		inner join SITMOBRAHOJE ON (SITMOBRAHOJE.SITMOBRAHOJE = PONTO.SITMOBRAHOJE)
		inner join RELACAOENTIDADE RELFUNC on (RELFUNC.RELACAOENTIDADE=PONTO.COLABORADOR)
		inner join ENTIDADE ENTFUNC on (ENTFUNC.ENTIDADE=RELFUNC.PAPEL1)
		inner  join SITMAODEOBRAFUNC on (SITMAODEOBRAFUNC.FUNCIONARIO= PONTO.COLABORADOR
										and SITMAODEOBRAFUNC.DTINICIO<= PONTO.DATA
										and (SITMAODEOBRAFUNC.DTFIM>= PONTO.DATA  or SITMAODEOBRAFUNC.DTFIM is null)
										and SITMAODEOBRAFUNC.SITUACAO = 1)
		inner join SITUACAOMOBRA SITUACAOMOBRATEMP	on (SITUACAOMOBRATEMP.SITUACAOMOBRA = SITMAODEOBRAFUNC.SITUACAOMOBRATEMP)
													on (PONTO.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA AND PONTO.DATA=PONTOVAGA.DATA)
		left join LIGAPOSTOLOCALAREASUPER
		left join RELACAOENTIDADE RELAREA on (RELAREA.RELACAOENTIDADE =  LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)
		left join ENTIDADE ENTAREA	on (ENTAREA.ENTIDADE = RELAREA.PAPEL1)
									on (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO
										and LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=TURNOTRABALHO.TURNOTRABALHO
										and LIGAPOSTOLOCALAREASUPER.SITUACAO=1)
		left join RELACAOENTIDADE RELSUP
		inner join ENTIDADE ENTSUP	ON (ENTSUP.ENTIDADE=RELSUP.PAPEL1)
									ON (RELSUP.RELACAOENTIDADE=LOCALSERVICOEMP.GESTOROPERACIONAL)
		left join BLOQUEIACOBERTURA on (BLOQUEIACOBERTURA.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO
		and BLOQUEIACOBERTURA.SITUACAO=1
										AND BLOQUEIACOBERTURA.DTINICIO<=PONTOVAGA.DATA AND (BLOQUEIACOBERTURA.DTFIM IS NULL
										OR BLOQUEIACOBERTURA.DTFIM>=PONTOVAGA.DATA))
		LEFT JOIN RELACAOENTAUX RELAUXENDERECO
		INNER JOIN ENTIDADEAUX ENTAUXENDERECO ON (ENTAUXENDERECO.ENTIDADEAUX=RELAUXENDERECO.ENTIDADEAUX)
		INNER JOIN ENDERECO ENDERECOPOSTO ON (ENDERECOPOSTO.ENDERECO=ENTAUXENDERECO.ENTIDADEAUX)
		INNER JOIN TPLOGRADOURO TPLOGRADOUROPOSTO	ON (TPLOGRADOUROPOSTO.TPLOGRADOURO=ENDERECOPOSTO.TPLOGRADOURO)
													ON (RELAUXENDERECO.RELACAOENTIDADE=LOCALSERVICO.LOCALSERVICO
														AND RELAUXENDERECO.SITUACAO=1
														AND RELAUXENDERECO.PRINCIPAL=1
														AND RELAUXENDERECO.TIPOAUXILIAR=3)
		LEFT OUTER JOIN LOCALIDADE ON (LOCALSERVICO.LOCALIDADE_ISS = LOCALIDADE.LOCALIDADE)
			WHERE   BLOQUEIACOBERTURA.BLOQUEIACOBERTURA IS NULL
					AND PONTOVAGA.DATA BETWEEN @DATA_INICIO AND @DATA_FIM

			union


select distinct
	VAGAITEMCONTRATO.VAGAITEMCONTRATO,
	LOCALSERVICOEMP.EMPRESA AS COD_EMPRESA,
	ENTEMPRESA.NOMERESUMIDO AS DESCEMPRESA,
	LOCALSERVICO.BASEOPERACIONAL,
	ENTBASEOP.NOMERESUMIDO AS DESCBASEOPERACIONAL,
	PONTOVAGA.DATA,
	RELENTCLI.CODIGO AS COD_CLIENTE,
	ENTCLI.NOMERESUMIDO AS CLIENTE,
	RELLOCAL.CODIGO AS COD_LOCAL,
	ENTLOCAL.NOMERESUMIDO AS LOCALSERVICO,
	ENTPOSTO.NOMERESUMIDO AS POSTO,
	PONTOVAGA.VAGAITEMCONTRATO AS 'PONTOVAGA',
	TURNOTRABALHO.DESCRICAO AS DESCTURNO,
	CARGO.CARGO AS COD_CARGO,
	CARGO.DESCRICAO AS DESCCARGO,
	ESCALATRABALHO.ESCALATRABALHO AS COD_ESCALA,
	ESCALATRABALHO.DESCRICAO AS ESCALA,
	RELFUNCGRUPOCOBERTURA.CODIGO AS RE,
	ENTFUNCGRUPOCOBERTURA.NOMERESUMIDO AS NOMEFUNC,
	SITUACAOMOBRATEMP.SITUACAOMOBRA AS COD_SITUACAO,
	SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL AS SITUACAO,
	SITMOBRAHOJE.SITMOBRAHOJE AS COD_SITMOBRAHOJE,
	SITMOBRAHOJE.DESCRICAOAMIGAVEL AS SITUACAO_PONTO,
	LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO AS CODAREASUPERVISAO,
	ENTAREA.NOMECOMPLETO AS NOMEAREASUPERVISAO,
	RELSUP.CODIGO AS COD_GESTOR_OP,
	ENTSUP.NOMECOMPLETO AS NOME_GESTOR_OP,
	MOTMOVIMENTACAO.DESCRICAO AS MOTIVO_IMPLANTACAO,
	VAGAITEMCONTRATO.ORIGEMVAGA AS ORIGEMVAGA,
	CASE
		WHEN CONTRATO.TPMENSALEVENTO = 1 THEN 'MENSAL'
		WHEN CONTRATO.TPMENSALEVENTO = 2 THEN 'EVENTO'
		WHEN CONTRATO.TPMENSALEVENTO = 3 THEN 'EVENTO PRÉ-DETERMINADO'
		WHEN CONTRATO.TPMENSALEVENTO = 4 THEN 'MENSAL PRÉ-DETERMINADO'
	END AS TPMENSALEVENTO,  PONTOVAGA.SITUACAOCOBERTA,
	case
		when PONTOVAGA.SITUACAOCOBERTA=0 then 'DESCOBERTA'
		when PONTOVAGA.SITUACAOCOBERTA=2 then 'BLOQUEADA'
		when PONTOVAGA.SITUACAOCOBERTA=3 then 'JUSTIFICADA'
	end DESCSITUACAOCOBERTA,
	CASE
		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. PAR. FUNC.'
			OR SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. PAR. CLI.' THEN 'Saida Antecipada'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'ATIVO' THEN 'Correção'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'INSS' THEN 'Falta'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'FÉRIAS' THEN 'Férias'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'RECICLAGEM' THEN 'Reciclagem'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'SUSPENSÃO' THEN 'Suspensão'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'TRABALHO'
			AND SITUACAOMOBRATEMP.DESCRICAOAMIGAVEL = 'FERIAS TRAB.' THEN 'Correção'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL IS NULL THEN 'Posto Vago'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. TOT. COB.'
			OR  SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. PAR. COB.'
			OR  SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'FOLGA CANCELADA'	THEN 'Remanejamento'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'FALTA'			THEN 'Falta'

		WHEN SITMOBRAHOJE.DESCRICAOAMIGAVEL = 'LIB. TOTAL'		THEN 'Folga'
	end as 'MotivoPV',
	PONTOVAGA.MOTVGDESCOBERTA AS COD_MOTIVO_DESCOBERTA,
	ITENSCONTRATO.DESCRICAOFISCAL,
	ENDERECOPOSTO.CEP CEP_POSTO,
	TPLOGRADOUROPOSTO.NOMETPLOGRADOURO TIPO_LOGRADOURO_POSTO,
	ENDERECOPOSTO.NOMELOGRADOURO LOGRADOURO_POSTO,
	ENDERECOPOSTO.NUMERO NUMERO_POSTO,
	ENDERECOPOSTO.COMPLEMENTO COMPLEMENTO_POSTO,
	ENDERECOPOSTO.NOMEBAIRRO BAIRRO_POSTO,
	ENDERECOPOSTO.SIGLAUF UF_POSTO,
	ENDERECOPOSTO.PONTOREFERENCIA PONTO_REFERENCIA_POSTO,
	LOCALIDADE.NOMELOCALIDADE CIDADE_POSTO
	from
		LOCALSERVICOEMP
		inner join RELACAOENTIDADE RELEMPRESA on (RELEMPRESA.RELACAOENTIDADE=LOCALSERVICOEMP.EMPRESA)
		inner join ENTIDADE ENTEMPRESA on (ENTEMPRESA.ENTIDADE=RELEMPRESA.PAPEL1)
		inner join LOCALSERVICO on (LOCALSERVICO.LOCALSERVICO=LOCALSERVICOEMP.LOCALSERVICO)
		inner join RELACAOENTIDADE RELBASEOP ON (RELBASEOP.RELACAOENTIDADE=LOCALSERVICO.BASEOPERACIONAL)
		inner join ENTIDADE ENTBASEOP ON (ENTBASEOP.ENTIDADE=RELBASEOP.PAPEL1)
		inner join POSTOLOCALSERVICO on (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)
		inner join VAGAITEMCONTRATO on (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO)
		inner join CLIENTE on (CLIENTE.CLIENTE=VAGAITEMCONTRATO.CLIENTE AND (CLIENTE.TIPOCLIENTE=1 or VAGAITEMCONTRATO.ORIGEMVAGA=10))
		INNER JOIN CONTRATO ON CONTRATO.CONTRATO = VAGAITEMCONTRATO.CONTRATO
		inner join PONTOVAGA on (PONTOVAGA.VAGAITEMCONTRATOEFETIVO=VAGAITEMCONTRATO.VAGAITEMCONTRATO and PONTOVAGA.SITTRABALHO=1)
		inner join LIGAVGITEMCONTRATO on (VAGAITEMCONTRATO.VAGAITEMCONTRATO=LIGAVGITEMCONTRATO.VAGAITEMCONTRATO
													and LIGAVGITEMCONTRATO.DTIMPLANTACAO<=PONTOVAGA.DATA
													and ((LIGAVGITEMCONTRATO.DTENCERRAMENTO is null)
													or (LIGAVGITEMCONTRATO.DTENCERRAMENTO>=PONTOVAGA.data)))
		inner join COMPOSICAOITENSCONTRATO on (LIGAVGITEMCONTRATO.COMPOSICAOITENSCONTRATO=COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO)
		inner join ITENSCONTRATO on (COMPOSICAOITENSCONTRATO.ITENSCONTRATO=ITENSCONTRATO.ITENSCONTRATO)
		inner join TURNOTRABALHO on (TURNOTRABALHO.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO)
		inner join CARGO on (CARGO.CARGO=VAGAITEMCONTRATO.CARGO)
		inner join RELACAOENTIDADE RELLOCAL on (RELLOCAL.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)
		inner join ENTIDADE ENTLOCAL on (ENTLOCAL.ENTIDADE=RELLOCAL.PAPEL1)
		inner join RELACAOENTIDADE RELENTCLI on (RELENTCLI.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)
		inner join ENTIDADE ENTCLI on (ENTCLI.ENTIDADE=RELENTCLI.PAPEL1)
		inner join RELACAOENTIDADE RELPOSTO on (RELPOSTO.RELACAOENTIDADE=POSTOLOCALSERVICO.POSTOSERVICO)
		inner join ENTIDADE ENTPOSTO on (ENTPOSTO.ENTIDADE=RELPOSTO.PAPEL1)
		inner join ESCALATRABALHO on (ESCALATRABALHO.ESCALATRABALHO=VAGAITEMCONTRATO.ESCALATRABALHO)
		left join LIGAPOSTOLOCALAREASUPER
		left join RELACAOENTIDADE RELAREA on (RELAREA.RELACAOENTIDADE =  LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)
		left join ENTIDADE ENTAREA	on (ENTAREA.ENTIDADE = RELAREA.PAPEL1)
									on (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO
										and LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=TURNOTRABALHO.TURNOTRABALHO
										and LIGAPOSTOLOCALAREASUPER.SITUACAO=1)
		left join RELACAOENTIDADE RELSUP
		inner join ENTIDADE ENTSUP ON (ENTSUP.ENTIDADE=RELSUP.PAPEL1)    ON (RELSUP.RELACAOENTIDADE=LOCALSERVICOEMP.GESTOROPERACIONAL)
		inner join BLOQUEIACOBERTURA on (BLOQUEIACOBERTURA.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO and BLOQUEIACOBERTURA.SITUACAO=1
												AND BLOQUEIACOBERTURA.DTINICIO<=PONTOVAGA.DATA
												AND (BLOQUEIACOBERTURA.DTFIM IS NULL
												OR BLOQUEIACOBERTURA.DTFIM>=PONTOVAGA.DATA))
		inner join VAGASGRUPOCOBERTURA on (VAGASGRUPOCOBERTURA.BLOQUEIACOBERTURA=BLOQUEIACOBERTURA.BLOQUEIACOBERTURA
											and VAGASGRUPOCOBERTURA.DTIMPLANTACAO<=PONTOVAGA.DATA
											and (VAGASGRUPOCOBERTURA.DTENCERRAMENTO IS NULL
											OR VAGASGRUPOCOBERTURA.DTENCERRAMENTO>=PONTOVAGA.DATA))
		inner join LIGAVAGACOBERTURA on (LIGAVAGACOBERTURA.GRUPOCOBERTURA=VAGASGRUPOCOBERTURA.GRUPOCOBERTURA and LIGAVAGACOBERTURA.SITUACAO=1)
		LEFT JOIN ALOCACAOMAODEOBRA
		INNER JOIN MOTMOVIMENTACAO	ON (MOTMOVIMENTACAO.MOTMOVIMENTACAO=ALOCACAOMAODEOBRA.MOTIVOIMPLANTACAO)
									ON (ALOCACAOMAODEOBRA.VAGAITEMCONTRATO=LIGAVAGACOBERTURA.VAGAITEMCONTRATO
										AND ALOCACAOMAODEOBRA.SITALOCACAO=1
										and ALOCACAOMAODEOBRA.DTINICIO<= PONTOVAGA.DATA
										and (ALOCACAOMAODEOBRA.DTFIM>= PONTOVAGA.DATA
										or ALOCACAOMAODEOBRA.DTFIM is null))
		left join PONTO PONTOGRUPOCOBERTURA
		inner join RELACAOENTIDADE RELFUNCGRUPOCOBERTURA on (RELFUNCGRUPOCOBERTURA.RELACAOENTIDADE=PONTOGRUPOCOBERTURA.COLABORADOR)
		inner join ENTIDADE ENTFUNCGRUPOCOBERTURA on (ENTFUNCGRUPOCOBERTURA.ENTIDADE=RELFUNCGRUPOCOBERTURA.PAPEL1)
		inner join SITMOBRAHOJE ON (SITMOBRAHOJE.SITMOBRAHOJE = PONTOGRUPOCOBERTURA.SITMOBRAHOJE)
		inner join RELACAOENTIDADE RELFUNC on (RELFUNC.RELACAOENTIDADE=PONTOGRUPOCOBERTURA.COLABORADOR and RELFUNC.SITUACAO=1)
		inner join ENTIDADE ENTFUNC on (ENTFUNC.ENTIDADE=RELFUNC.PAPEL1)
		inner join SITMAODEOBRAFUNC on (SITMAODEOBRAFUNC.FUNCIONARIO= PONTOGRUPOCOBERTURA.COLABORADOR
										and SITMAODEOBRAFUNC.DTINICIO<= PONTOGRUPOCOBERTURA.DATA
										and (SITMAODEOBRAFUNC.DTFIM>= PONTOGRUPOCOBERTURA.DATA
										or SITMAODEOBRAFUNC.DTFIM is null)
										and SITMAODEOBRAFUNC.SITUACAO = 1)
		inner join SITUACAOMOBRA SITUACAOMOBRATEMP	on (SITUACAOMOBRATEMP.SITUACAOMOBRA = SITMAODEOBRAFUNC.SITUACAOMOBRATEMP)
													on (PONTOGRUPOCOBERTURA.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA
														and PONTOGRUPOCOBERTURA.DATA=PONTOVAGA.DATA)
		LEFT JOIN RELACAOENTAUX RELAUXENDERECO
		INNER JOIN ENTIDADEAUX ENTAUXENDERECO ON (ENTAUXENDERECO.ENTIDADEAUX=RELAUXENDERECO.ENTIDADEAUX)
		INNER JOIN ENDERECO ENDERECOPOSTO ON (ENDERECOPOSTO.ENDERECO=ENTAUXENDERECO.ENTIDADEAUX)
		INNER JOIN TPLOGRADOURO TPLOGRADOUROPOSTO	ON (TPLOGRADOUROPOSTO.TPLOGRADOURO=ENDERECOPOSTO.TPLOGRADOURO)
													ON (RELAUXENDERECO.RELACAOENTIDADE=LOCALSERVICO.LOCALSERVICO
														AND RELAUXENDERECO.SITUACAO=1
														AND RELAUXENDERECO.PRINCIPAL=1
														AND RELAUXENDERECO.TIPOAUXILIAR=3)
		LEFT OUTER JOIN LOCALIDADE ON (LOCALSERVICO.LOCALIDADE_ISS = LOCALIDADE.LOCALIDADE)
			WHERE
				NOT EXISTS (
							SELECT PONTO.PONTO
								FROM  PONTO
									WHERE
										PONTO.VAGAITEMCONTRATO=LIGAVAGACOBERTURA.VAGAITEMCONTRATO
										AND PONTO.DATA=PONTOVAGA.DATA
										AND PONTO.SITMOBRAHOJE IN (1,2,3,4,5)  )
														AND PONTOVAGA.DATA BETWEEN @DATA_INICIO AND @DATA_FIM

)

-- =====================================================================
-- FILTRO FINAL: Remove postos que aparecem com funcionário coberto
-- Se o mesmo VAGAITEMCONTRATO + DATA tiver NOMEFUNC preenchido
-- em qualquer linha do UNION, o posto está coberto e deve ser excluído
-- =====================================================================
SELECT *
FROM RESULTADO R
WHERE NOT EXISTS (
    SELECT 1
    FROM RESULTADO R2
    WHERE R2.VAGAITEMCONTRATO = R.VAGAITEMCONTRATO
      AND R2.DATA             = R.DATA
      AND R2.VAGAITEMCONTRATO <> R.VAGAITEMCONTRATO
)
ORDER BY
	DESCEMPRESA,
	BASEOPERACIONAL,
	DATA,
	CLIENTE,
	LOCALSERVICO,
	POSTO,
	VAGAITEMCONTRATO;