version: "3.7"
services:

## --------------------------- DASHBOARD CSC --------------------------- ##

  dashboard_frontend:
    image: dashboard-csc-local:latest ## Versão do Frontend (Build Local)

    networks:
      - pportz ## Nome da rede interna

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard_csc.rule=Host(`dashboard.csc.pportz.com.br`) ## Url do Dashboard
        - traefik.http.routers.dashboard_csc.entrypoints=websecure
        - traefik.http.routers.dashboard_csc.priority=10
        - traefik.http.routers.dashboard_csc.tls.certresolver=letsencryptresolver
        - traefik.http.routers.dashboard_csc.service=dashboard_frontend
        - traefik.http.services.dashboard_frontend.loadbalancer.server.port=80
        - traefik.http.services.dashboard_frontend.loadbalancer.passHostHeader=1

## --------------------------- DASHBOARD CSC --------------------------- ##

networks:
  pportz: ## Nome da rede interna
    external: true
    name: pportz
