version: '3.8'

services:
  frontend:
    image: dashboard-csc-local:latest
    networks:
      - portz
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard-csc.rule=Host(`dashboard.csc.pportz.com.br`)"
        - "traefik.http.routers.dashboard-csc.entrypoints=websecure"
        - "traefik.http.routers.dashboard-csc.tls=true"
        - "traefik.http.routers.dashboard-csc.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.dashboard-csc.loadbalancer.server.port=80"

networks:
  portz:
    external: true
