DECLARE @DATA DATE
	SELECT @DATA=GETDATE()
SELECT
	CTLRETDOCUMENTO.DTGERACAO,
	CTLRETDOCUMENTO.DTRETORNO,
	CTLRETDOCUMENTO.ANOMES,
	CONVERT(VARCHAR(7),
	SUBSTRING(CONVERT(VARCHAR(6), CTLRETDOCUMENTO.ANOMES), 5, 2)  + '/' + SUBSTRING(CONVERT(VARCHAR(6), CTLRETDOCUMENTO.ANOMES), 1, 4) ) AS MES_ANO_FORMATADO,
	CASE CTLRETDOCUMENTO.SITUACAO
		WHEN 1 THEN 'PENDENTE'
		WHEN 2 THEN 'CONCLUÍDO'
		WHEN 3 THEN 'CANCELADO'
		WHEN 4 THEN 'LIDO'
	END AS SITUACAO,
	CASE CTLRETDOCUMENTO.SITUACAO
        WHEN 1 THEN 'PENDENTE'
        WHEN 2 THEN 'CONCLUÍDO'
        WHEN 3 THEN 'PENDENTE'
        WHEN 4 THEN 'PENDENTE'
    END AS STATUS,
	ENTIDADE_EMPRESA.NOMERESUMIDO AS EMPRESA,
	ENTIDADE_FUNCIONARIO.NOMECOMPLETO AS NOME_FUNCIONARIO,
	ENTIDADE_USUARIO_GERACAO.NOMECOMPLETO AS USUARIO_GERACAO,
	ENTIDADE_USUARIO_RETORNO.NOMECOMPLETO AS USUARIO_RETORNO,
	RELACAOENTIDADE_FUNCIONARIO.CODIGO AS RE_FUNCIONARIO,
	ENTIDADE_EMPRESA.NOMERESUMIDO + CONVERT(VARCHAR(6), CTLRETDOCUMENTO.ANOMES)  AS QUEBRA_EMPRESA_ANOMES ,
	RELCLIENTE.RELACAOENTIDADE RELCLIENTE,
	RELLOCAL.RELACAOENTIDADE RELLOCAL,
	RELAREA.RELACAOENTIDADE RELAREA,
	ENTCLIENTE.NOMERESUMIDO AS CLIENTE ,
	ENTLOCAL.NOMERESUMIDO   AS LOCAL ,
	TURNOTRABALHO.DESCRICAO AS TURNO,
	ENTAREA.NOMERESUMIDO    AS AREASUPERVISAO
	FROM
		(SELECT
			2 AS TIPOCONTROLE,
			ARQUIVO.DTINICIO AS DTGERACAO,
			ARQUIVO.DTASSINADO AS DTRETORNO,
			CONVERT(VARCHAR(6), ARQUIVO.DTCOMPETENCIA, 112) AS ANOMES,
			RELACAOENTIDADE.PAPEL2 EMPRESA,
			RELACAOENTIDADE.RELACAOENTIDADE FUNCIONARIO,
			ARQUIVO.USUARIO USUGERACAO,
			(select USUARIO.USUARIO
				from USUARIO WITH (NOLOCK) where USUARIO.RELACAOENTIDADE = RELACAOENTIDADE.RELACAOENTIDADE) USURETORNO,
			CASE  COALESCE(ARQUIVO.DTVISUALIZADOAPP,0,1)
				WHEN 0 THEN  1
				ELSE
					CASE COALESCE(ARQUIVO.DTREJEITADO,0,1)
						WHEN 0 THEN CASE COALESCE(ARQUIVO.DTASSINADO,0,1)
						WHEN 0 THEN 4
						ELSE 2
					END
					ELSE 3
				END
			END SITUACAO
		FROM ARQUIVO WITH (NOLOCK) INNER JOIN RELACAOENTIDADE WITH (NOLOCK) ON (ARQUIVO.DONOARQUIVO=RELACAOENTIDADE.DONOARQUIVO AND RELACAOENTIDADE.SITUACAO=1 AND RELACAO = 6)
			WHERE ARQUIVO.ORIGEM = 1
				AND ARQUIVO.SITUACAO = 1
				AND ARQUIVO.TPARQUIVO =  2
				AND ARQUIVO.CONTEUDOARQUIVO = 6

			UNION

			SELECT
				1 AS TIPOCONTROLE,
				CTLRETDOCUMENTO.DTGERACAO,
				CTLRETDOCUMENTO.DTRETORNO,
				CTLRETDOCUMENTO.ANOMES,
				CTLRETDOCUMENTO.EMPRESA ,
				CTLRETDOCUMENTO.FUNCIONARIO,
				CTLRETDOCUMENTO.USUGERACAO,
				CTLRETDOCUMENTO.USURETORNO,
				CTLRETDOCUMENTO.SITUACAO
				FROM CTLRETDOCUMENTO WITH (NOLOCK)) AS CTLRETDOCUMENTO
	INNER JOIN RELACAOENTIDADE RELACAOENTIDADE_EMPRESA WITH (NOLOCK)
		ON (RELACAOENTIDADE_EMPRESA.RELACAO = 3
			AND CTLRETDOCUMENTO.EMPRESA =  RELACAOENTIDADE_EMPRESA.RELACAOENTIDADE)
	INNER JOIN ENTIDADE ENTIDADE_EMPRESA WITH (NOLOCK)
		ON (RELACAOENTIDADE_EMPRESA.PAPEL1 = ENTIDADE_EMPRESA.ENTIDADE)
	INNER JOIN RELACAOENTIDADE RELACAOENTIDADE_FUNCIONARIO WITH (NOLOCK)
		ON (RELACAOENTIDADE_FUNCIONARIO.RELACAO = 6
			and RELACAOENTIDADE_FUNCIONARIO.SITUACAO=1
			AND CTLRETDOCUMENTO.FUNCIONARIO = RELACAOENTIDADE_FUNCIONARIO.RELACAOENTIDADE)
	INNER JOIN ENTIDADE ENTIDADE_FUNCIONARIO WITH (NOLOCK)
		ON (RELACAOENTIDADE_FUNCIONARIO.PAPEL1 = ENTIDADE_FUNCIONARIO.ENTIDADE)
	INNER JOIN RELACAOENTIDADE RELACAOENTIDADE_USUARIO_GERACAO WITH (NOLOCK)
		ON RELACAOENTIDADE_USUARIO_GERACAO.RELACAO = 100
			AND CTLRETDOCUMENTO.USUGERACAO = RELACAOENTIDADE_USUARIO_GERACAO.RELACAOENTIDADE
	INNER JOIN ENTIDADE ENTIDADE_USUARIO_GERACAO WITH (NOLOCK)
		ON (RELACAOENTIDADE_USUARIO_GERACAO.PAPEL1 = ENTIDADE_USUARIO_GERACAO.ENTIDADE)
	LEFT JOIN RELACAOENTIDADE RELACAOENTIDADE_USUARIO_RETORNO WITH (NOLOCK)
		INNER JOIN ENTIDADE ENTIDADE_USUARIO_RETORNO WITH (NOLOCK)
			ON (RELACAOENTIDADE_USUARIO_RETORNO.PAPEL1 = ENTIDADE_USUARIO_RETORNO.ENTIDADE)
			ON (RELACAOENTIDADE_USUARIO_RETORNO.RELACAO = 100
				AND CTLRETDOCUMENTO.USURETORNO = RELACAOENTIDADE_USUARIO_RETORNO.RELACAOENTIDADE)
	INNER JOIN FUNCIONARIO WITH (NOLOCK) ON (FUNCIONARIO.FUNCIONARIO=CTLRETDOCUMENTO.FUNCIONARIO)
	LEFT JOIN ALOCACAOMAODEOBRA ULTIMAALOCACAO WITH (NOLOCK)
		INNER JOIN VAGAITEMCONTRATO ULTIMAVAGA WITH (NOLOCK)
			ON (ULTIMAVAGA.VAGAITEMCONTRATO=ULTIMAALOCACAO.VAGAITEMCONTRATO)
	INNER JOIN RELACAOENTIDADE RELCLIENTE WITH (NOLOCK)
		ON (RELCLIENTE.RELACAOENTIDADE=ULTIMAVAGA.CLIENTE)
	INNER JOIN ENTIDADE ENTCLIENTE WITH (NOLOCK)
		ON (ENTCLIENTE.ENTIDADE = RELCLIENTE.PAPEL1)
	INNER JOIN RELACAOENTIDADE RELLOCAL WITH (NOLOCK)
		ON (RELLOCAL.RELACAOENTIDADE=ULTIMAVAGA.LOCALSERVICO)
	INNER JOIN ENTIDADE ENTLOCAL WITH (NOLOCK)
		ON (ENTLOCAL.ENTIDADE = RELLOCAL.PAPEL1)
	INNER JOIN TURNOTRABALHO WITH (NOLOCK) ON (TURNOTRABALHO.TURNOTRABALHO=ULTIMAVAGA.TURNOTRABALHO)
	LEFT JOIN LIGAPOSTOLOCALAREASUPER WITH (NOLOCK) ON (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=ULTIMAVAGA.POSTOLOCALSERVICO
			AND LIGAPOSTOLOCALAREASUPER.SITUACAO=1
			AND LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=ULTIMAVAGA.TURNOTRABALHO)
	LEFT JOIN RELACAOENTIDADE RELAREA WITH (NOLOCK)
		ON (RELAREA.RELACAOENTIDADE=LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)
		ON (ULTIMAALOCACAO.COLABORADOR=FUNCIONARIO.FUNCIONARIO
			AND ULTIMAALOCACAO.SITALOCACAO=1
			AND ULTIMAALOCACAO.TPALOCACAO=1
			AND ULTIMAALOCACAO.DTINICIO<=
				CASE
					WHEN FUNCIONARIO.DTDEMISSAO IS NULL THEN CAST(GETDATE() AS DATE)
					ELSE FUNCIONARIO.DTDEMISSAO
				END
			AND (ULTIMAALOCACAO.DTFIM IS NULL OR ULTIMAALOCACAO.DTFIM>=
				CASE
					WHEN FUNCIONARIO.DTDEMISSAO IS NULL THEN CAST(GETDATE() AS DATE)
					ELSE FUNCIONARIO.DTDEMISSAO
				END)
			)
	LEFT JOIN ENTIDADE ENTAREA WITH (NOLOCK)
		ON (ENTAREA.ENTIDADE = RELAREA.PAPEL1)
	LEFT JOIN PONTO WITH (NOLOCK) ON (FUNCIONARIO.FUNCIONARIO=PONTO.COLABORADOR
			AND PONTO.DATA=@DATA
			AND PONTO.SITUACAOMOBRA=10)
	WHERE   CTLRETDOCUMENTO.ANOMES BETWEEN @ANOMESINI AND @ANOMESFIM
	ORDER BY
		ENTIDADE_EMPRESA.NOMERESUMIDO,
		CTLRETDOCUMENTO.ANOMES,
		ENTCLIENTE.NOMERESUMIDO,
		ENTLOCAL.NOMERESUMIDO,
		TURNOTRABALHO.DESCRICAO,
		ENTAREA.NOMERESUMIDO,
		ENTIDADE_FUNCIONARIO.NOMECOMPLETO,
		CTLRETDOCUMENTO.DTGERACAO,
		CTLRETDOCUMENTO.DTRETORNO
