SELECT DISTINCT
    ENTEMP.NOMECOMPLETO AS EMPRESA,
    ENTBASEOPER.NOMECOMPLETO AS BASEOPERACIONAL,
    RELCLIENTE.CODIGO AS CODCLIENTE,
    ENTCLIENTE.NOMECOMPLETO AS NOMECOMPLETO_CLIENTE,
    ENTCLIENTE.NOMERESUMIDO AS NOMERESUMIDO_CLIENTE,
    RELLOCAL.CODIGO AS CODLOCAL,
    ENTLOCAL.NOMECOMPLETO AS NOMECOMPLETO_LOCAL,
    ENTLOCAL.NOMERESUMIDO AS NOMERESUMIDO_LOCAL,
    UPPER(UF.NOME_UF) UF,
    UPPER(ENDERECO.NOMELOCALIDADE) LOCALIDADE,
    UPPER(ENDERECO.NOMEBAIRRO) BAIRRO,
    UPPER(TPLOGRADOURO.NOMETPLOGRADOURO + ' ' + ENDERECO.NOMELOGRADOURO) LOGRADOURO,
    ENDERECO.NUMERO,
    UPPER(ENDERECO.PONTOREFERENCIA) PONTOREFERENCIA,
    UPPER(ZONA.DESCRICAO) AS ZONA,
    UPPER(ENDERECO.COMPLEMENTO) AS COMPLEMENTO,
    ENDERECO.CEP,
    TELEFONE.DDI,
    TELEFONE.DDD,
    TELEFONE.NUMERO AS TELEFONE,
    TELEFONE.RAMAL,
    EMAIL.DESCRICAO AS EMAIL,
    ENTCONTATO.NOMECOMPLETO AS CONTATOOPER,
    ENTAREA.NOMECOMPLETO AS AREASUPERVISAO,
    ENTAREA.NOMECOMPLETO AS SUPERVISOR

FROM
    ENTIDADE ENTCLIENTE

    INNER JOIN RELACAOENTIDADE RELCLIENTE
        ON (ENTCLIENTE.ENTIDADE = RELCLIENTE.PAPEL1
            AND RELCLIENTE.RELACAO = 300)

    INNER JOIN CLIENTE
        ON (CLIENTE.CLIENTE = RELCLIENTE.RELACAOENTIDADE
            AND CLIENTE.SITUACAOCLIENTE IN (2, 3))

    INNER JOIN RELACAOENTIDADE RELLOCAL
        ON (RELCLIENTE.RELACAOENTIDADE = RELLOCAL.PAPEL2
            AND RELLOCAL.SITUACAO = 1)

    INNER JOIN ENTIDADE ENTLOCAL
        ON (RELLOCAL.PAPEL1 = ENTLOCAL.ENTIDADE)

    INNER JOIN LOCALSERVICO
        ON (LOCALSERVICO.LOCALSERVICO = RELLOCAL.RELACAOENTIDADE)

    INNER JOIN ITENSCONTRLOCAL
        ON (LOCALSERVICO.LOCALSERVICO = ITENSCONTRLOCAL.LOCALSERVICO )

    INNER JOIN ITENSCONTRATO
        ON (ITENSCONTRLOCAL.ITENSCONTRATO = ITENSCONTRATO.ITENSCONTRATO
            AND ITENSCONTRATO.SITUACAO = 1)

    INNER JOIN CONTRATO
        ON (ITENSCONTRATO.CONTRATO = CONTRATO.CONTRATO)

    INNER JOIN RELACAOENTIDADE RELEMP
        ON (RELEMP.RELACAOENTIDADE = CONTRATO.EMPRESA
            AND RELEMP.SITUACAO = 1)

    INNER JOIN ENTIDADE ENTEMP
        ON (ENTEMP.ENTIDADE = RELEMP.PAPEL1)

    INNER JOIN RELACAOENTIDADE RELBASEOPER
        ON (RELBASEOPER.RELACAOENTIDADE = LOCALSERVICO.BASEOPERACIONAL
            AND RELBASEOPER.SITUACAO = 1)

    INNER JOIN ENTIDADE ENTBASEOPER
        ON (ENTBASEOPER.ENTIDADE = RELBASEOPER.PAPEL1)

    INNER JOIN RELACAOENTAUX RELENTAUX_ENDERECO
        ON (RELLOCAL.RELACAOENTIDADE = RELENTAUX_ENDERECO.RELACAOENTIDADE
            AND RELENTAUX_ENDERECO.PRINCIPAL = 1)

    INNER JOIN ENTIDADEAUX ENTAUX_ENDERECO
        ON (RELENTAUX_ENDERECO.ENTIDADEAUX = ENTAUX_ENDERECO.ENTIDADEAUX
            AND ENTAUX_ENDERECO.TIPOAUXILIAR = 3)

    INNER JOIN ENDERECO
        ON (ENTAUX_ENDERECO.ENTIDADEAUX = ENDERECO.ENDERECO)

    LEFT JOIN TPLOGRADOURO
        ON (TPLOGRADOURO.TPLOGRADOURO = ENDERECO.TPLOGRADOURO)

    LEFT JOIN ZONA
        ON (ZONA.ZONA = ENDERECO.ZONA)

    LEFT JOIN UF
        ON (UF.UF = ENDERECO.UF)

    LEFT JOIN RELACAOENTAUX RELACAOENTAUX_FONE
        INNER JOIN ENTIDADEAUX ENTIDADEAUX_FONE
            ON (RELACAOENTAUX_FONE.ENTIDADEAUX = ENTIDADEAUX_FONE.ENTIDADEAUX)
        INNER JOIN TELEFONE
            ON (ENTIDADEAUX_FONE.ENTIDADEAUX = TELEFONE.TELEFONE)
        ON (RELLOCAL.RELACAOENTIDADE = RELACAOENTAUX_FONE.RELACAOENTIDADE
            AND RELACAOENTAUX_FONE.PRINCIPAL = 1
            AND RELACAOENTAUX_FONE.TIPOAUXILIAR = 1)

    LEFT JOIN RELACAOENTAUX RELACAOENTAUX_CONTATO
        INNER JOIN ENTIDADEAUX ENTIDADEAUX_CONTATO
            ON (RELACAOENTAUX_CONTATO.ENTIDADEAUX = ENTIDADEAUX_CONTATO.ENTIDADEAUX)
        INNER JOIN CONTATO
            ON (CONTATO.CONTATO = ENTIDADEAUX_CONTATO.ENTIDADEAUX)
        INNER JOIN RELACAOENTIDADE RELCONTATO
            ON (RELCONTATO.RELACAOENTIDADE = CONTATO.RELACAOENTIDADE)
        INNER JOIN ENTIDADE ENTCONTATO
            ON (ENTCONTATO.ENTIDADE = RELCONTATO.PAPEL1)
        ON (RELLOCAL.RELACAOENTIDADE = RELACAOENTAUX_CONTATO.RELACAOENTIDADE
            AND RELACAOENTAUX_CONTATO.PRINCIPAL = 1
            AND RELACAOENTAUX_CONTATO.TIPOAUXILIAR = 4)

    LEFT JOIN RELACAOENTAUX RELACAOENTAUX_EMAIL
        INNER JOIN ENTIDADEAUX ENTIDADEAUX_EMAIL
            ON (RELACAOENTAUX_EMAIL.ENTIDADEAUX = ENTIDADEAUX_EMAIL.ENTIDADEAUX)
        INNER JOIN EMAIL
            ON (EMAIL.EMAIL = ENTIDADEAUX_EMAIL.ENTIDADEAUX)
        ON (RELLOCAL.RELACAOENTIDADE = RELACAOENTAUX_EMAIL.RELACAOENTIDADE
            AND RELACAOENTAUX_EMAIL.PRINCIPAL = 1
            AND RELACAOENTAUX_EMAIL.TIPOAUXILIAR = 2)

    LEFT JOIN LOCALSERVICOEMP
        INNER JOIN POSTOLOCALSERVICO
            ON (POSTOLOCALSERVICO.LOCALSERVICOEMP = LOCALSERVICOEMP.LOCALSERVICOEMP
                AND POSTOLOCALSERVICO.SITUACAO = 1)
        LEFT JOIN LIGAPOSTOLOCALAREASUPER
            LEFT JOIN RELACAOENTIDADE RELAREA
                ON (RELAREA.RELACAOENTIDADE = LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)
            LEFT JOIN ENTIDADE ENTAREA
                ON (ENTAREA.ENTIDADE = RELAREA.PAPEL1)
            ON (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO = POSTOLOCALSERVICO.POSTOLOCALSERVICO
                AND LIGAPOSTOLOCALAREASUPER.SITUACAO = 1)
        ON (LOCALSERVICO.LOCALSERVICO = LOCALSERVICOEMP.LOCALSERVICO
            AND CONTRATO.EMPRESA = LOCALSERVICOEMP.EMPRESA)

    INNER JOIN VERSAOCONTRATO
        ON (ITENSCONTRATO.VERSAOCONTRATO = VERSAOCONTRATO.VERSAOCONTRATO
            AND VERSAOCONTRATO.SITUACAOCONTR IN (3, 4))

WHERE
    RELCLIENTE.RELACAOENTIDADE >= 10000
ORDER BY
    ENTEMP.NOMECOMPLETO,
    ENTBASEOPER.NOMECOMPLETO,
    ENTAREA.NOMECOMPLETO,
    ENTCLIENTE.NOMECOMPLETO