-- Quadro Operacional — abas Excedente / Treinamento / Dobra (ocorrencias operacionais).
-- Nivel-ponto no periodo @DATA_INICIO..@DATA_FIM. So traz Resultado em
-- (EXCEDENTE, TREINAMENTO, Dobra) — filtrado na origem para ficar leve.
WITH CTR_FALTAABONADA AS   
	(SELECT   DISTINCT  SITFALTA.COLABORADOR
	,CASE   
		WHEN PONTO.HISTDISCIPLINAR IS NULL then  SITFALTA.DTINICIO   
		else HISTDISCIPLINAR.DTINICIOOCORRENCIA  
	END DTINICIO
	,CASE   
		WHEN PONTO.HISTDISCIPLINAR IS NULL then  SITFALTA.DTFIM   
		else HISTDISCIPLINAR.DTFIMOCORRENCIA  
	END DTFIM  
	FROM   SITMOBRAHOJEFUNC SITFALTA  
		INNER JOIN PONTO ON (PONTO.COLABORADOR=SITFALTA.COLABORADOR and PONTO.TPABONOPONTO=2  AND PONTO.DATA BETWEEN @DATA_INICIO AND @DATA_FIM)  
		left join HISTDISCIPLINAR ON (HISTDISCIPLINAR.HISTDISCIPLINAR=PONTO.HISTDISCIPLINAR and HISTDISCIPLINAR.SITUACAO=1)  
			WHERE  SITFALTA.COLABORADOR=PONTO.COLABORADOR AND SITFALTA.SITUACAO=1 AND SITFALTA.SITMOBRAHOJE=9  ) 
SELECT  
	RELEMPRESA.CODIGO COD_EMPRESA,
	ENTEMPRESA.NOMERESUMIDO NOMEEMPRESA,  
	RELFUNCIONARIO.RELACAOENTIDADE RELFUNC,  
	RELFUNCIONARIO.CODIGO RE,  
	ENTFUNCIONARIO.NOMECOMPLETO NOMEFUNCIONARIO,  
	PONTOVAGA.DATA,  PONTO.SITTRABALHO,  
	CASE      
		WHEN PONTOVAGA.FERIADO in (1,2,3,13,14) THEN 'F'   
		WHEN PONTOVAGA.FERIADO in (4,5,6,7,8) THEN 'P'   
		ELSE NULL   
	END AS DESCFERIADO,  
	RELCLI.CODIGO COD_CLIENTE,  
	ENTCLI.NOMERESUMIDO NOMECLIENTE,  ------
		CASE 
		WHEN ENTCLI.NOMERESUMIDO = 'PM RIBEIRÃO PRETO' AND  CARGO.DESCRICAO = 'AGENTE DE HIGIENIZAÇÃO'	THEN 'PM RIBEIRÃO PRETO - LIMPEZA'
		WHEN ENTCLI.NOMERESUMIDO = 'PM RIBEIRÃO PRETO' AND  CARGO.DESCRICAO = 'APOIO PEDAGOGICO'			THEN 'PM RIBEIRÃO PRETO - APOIO PEDAGOGICO'
		WHEN ENTCLI.NOMERESUMIDO = 'MARIO GATTI'		AND	 CARGO.DESCRICAO	IN ('AUXILIAR DE LIMPEZA',
																						'COLETOR DE RESIDUOS',
																						'LIDER DE LIMPEZA',
																						'LIMPADOR DE VIDROS')	THEN 'MARIO GATTI - LIMPEZA'
		WHEN ENTCLI.NOMERESUMIDO = 'MARIO GATTI'		AND CARGO.DESCRICAO = 'RECEPCIONISTA'				THEN 'MARIO GATTI - RECEPÇÃO'
		WHEN ENTCLI.NOMERESUMIDO = 'MARIO GATTI'		AND CARGO.DESCRICAO IN ('ENCARREGADO(A)'
																						,'SUPERVISOR(A)')		THEN 'MARIO GATTI - SUPERVISAO'
		WHEN ENTCLI.NOMERESUMIDO = 'PM DE PIRACICABA'	AND CARGO.DESCRICAO IN ('AGENTE DE HIGIENIZAÇÃO'
																					,'AUXILIAR DE LIMPEZA'	
																					,'ENCARREGADO(A)')			THEN 'PM DE PIRACICABA - LIMPEZA'
		WHEN ENTCLI.NOMERESUMIDO = 'PM DE PIRACICABA'	AND CARGO.DESCRICAO = 'ZELADOR'					THEN 'PM DE PIRACICABA - ZELADORIA'
		WHEN ENTCLI.NOMERESUMIDO = 'TIC TRENS S.A.'		AND CARGO.DESCRICAO IN ('AUXILIAR DE SERVIÇOS GERAIS',
																						'AGENTE DE HIGIENIZAÇÃO',
																						'LIDER DE LIMPEZA')		THEN 'TIC TRENS S.A. - LIMPEZA'
		WHEN ENTCLI.NOMERESUMIDO = 'TIC TRENS S.A.'		AND CARGO.DESCRICAO = 'CONTROLADOR DE ACESSO'		THEN 'TIC TRENS S.A. - CONTROLADOR'
		WHEN ENTCLI.NOMERESUMIDO = 'TIC TRENS S.A.'		AND CARGO.DESCRICAO IN ('ENCARREGADO(A)',
																						'SUPERVISOR(A)')		THEN 'TIC TRENS S.A. - SUPERVISÃO'

		WHEN ENTCLI.NOMERESUMIDO = 'TIC TRENS S.A.'		AND CARGO.DESCRICAO IN ('VIGILANTE PATRIMONIAL')		THEN 'TIC TRENS S.A. - VIGILANCIA'

		WHEN ENTCLI.NOMERESUMIDO = 'SME'					AND CARGO.DESCRICAO IN ('AGENTE DE HIGIENIZAÇÃO',
																						'AUXILIAR DE LIMPEZA',
																						'ENCARREGADO(A)',
																						'LIMPADOR DE VIDROS')	THEN 'SME - LIMPEZA'
		WHEN ENTCLI.NOMERESUMIDO = 'SME'					AND CARGO.DESCRICAO = 'VIGILANTE PATRIMONIAL'		THEN 'SME - VIGILANCIA'
		WHEN ENTCLI.NOMERESUMIDO = 'SME'					AND CARGO.DESCRICAO = 'PORTEIRO'					THEN 'SME - PORTARIA'			
		ELSE ENTCLI.NOMERESUMIDO 
		END AS NOMEFANTASIA,
	RELLOCALSERVICO.CODIGO COD_LOCAL,  
	ENTLOCALSERVICO.NOMERESUMIDO NOMELOCAL,  
	CASE 
        WHEN ALOCACAOMAODEOBRA.TPCOBERTURA = 2 THEN 'Dobra'
        ELSE ORIGEMVAGAEFETIVO.DESCRICAO
    END AS Resultado,
	ALOCACAOMAODEOBRA.TPCOBERTURA COD_COBERTURA,  
	CASE ALOCACAOMAODEOBRA.TPCOBERTURA      
		WHEN 1 THEN 'EFETIVO'      
		WHEN 2 THEN 'DOBRA'      
		WHEN 3 THEN 'COBERTURA'      
		WHEN 4 THEN 'CONVOCAÇÃO'      
		WHEN 5 THEN 'FT'  
	END AS DESCTPCOBERTURA,  
	ORIGEMVAGA.SIGLA ORIGEMVAGA, 
	ORIGEMVAGAEFETIVO.ORIGEMVAGA CODORIGEMVAGAEFETIVO, 
	ORIGEMVAGAEFETIVO.DESCRICAO DESVAGAEFETIVO,  
	CASE PARAMFOLHA.VALESCALATRABALHO   
		WHEN 1 THEN ESCALATRABALHOVGEFETIVO.ESCALATRABALHO   
		ELSE ESCALATRABALHO.ESCALATRABALHO  
	END AS COD_ESCALA, 
	CASE PARAMFOLHA.VALESCALATRABALHO   
		WHEN 1 THEN ESCALATRABALHOVGEFETIVO.DESCRICAO   
		ELSE ESCALATRABALHO.DESCRICAO  
	END AS DESCESCALA,  
	CASE PARAMFOLHA.VALESCALATRABALHO   
		WHEN 1 THEN ESCALATRABALHOVGEFETIVO.SIGLA   
		ELSE ESCALATRABALHO.SIGLA  
	END AS SIGLA,  
	SITUACAOMOBRA.SITUACAOMOBRA AS COD_SITUACAO_FUNC,  
	SITUACAOMOBRA.DESCRICAOAMIGAVEL AS DESCSITUACAO,  
	LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO AS CODAREASUPERVISAO,  
	ENTAREASUPERVISAO.NOMERESUMIDO AS AREASUPERVISAO,  
	CARGO.CARGO AS COD_CARGO,  
	CARGO.DESCRICAO AS DESC_CARGO,
	MOTALOC.MOTMOVIMENTACAO AS MOTIMPLANTA,  
	MOTALOC.DESCRICAO AS DESCIMPLA, 
	RELSUP.CODIGO AS COD_GESTOR,  
	ENTPOSTOLOCALSERVICO.NOMERESUMIDO AS POSTO, 
	VAGAITEMCONTRATO.VAGAITEMCONTRATO AS COD_VAGA,  
	CARGOVAGA.DESCRICAO CARGO_VAGA, 
	ITENSCONTRATO.DESCRICAOFISCAL DESC_FISCAL, 
	ITENSCONTRATO_EFETIVO.DESCRICAOFISCAL DESC_FISCAL_DIA, 
CONCAT_WS('; ',
        CASE WHEN PONTO.TPHRMRSAIALM IN (4,5) THEN 'Saída Almoço' END,
        CASE WHEN PONTO.TPHRMRRETALM IN (4,5) THEN 'Retorno Almoço' END,
        CASE WHEN PONTO.TPHRMRSAIDA  IN (4,5) THEN 'Saída Final' END
    ) AS Motivos_Correcao,
	PONTO.TPHRMRSAIALM,  
	PONTO.TPHRMRRETALM, 
	PONTO.TPHRMRSAIREFCOMPLEMENTAR,
	PONTO.TPHRMRRETREFCOMPLEMENTAR, 
	PONTO.TPHRMRSAIDA,  
	CASE   
		WHEN (coalesce(PONTO.TPHRMRSAIALM,0) IN (4,5)) 
			or (coalesce(PONTO.TPHRMRRETALM,0) IN (4,5)) 
			or (coalesce(PONTO.TPHRMRSAIREFCOMPLEMENTAR,0) IN (4,5)) 
			or (coalesce(PONTO.TPHRMRRETREFCOMPLEMENTAR,0) IN (4,5))
			or (coalesce(PONTO.TPHRMRSAIDA,0) IN (4,5)) THEN 'Correção'   
		ELSE ''  
	END Correção,    
	CASE CLIENTEEFETIVO.TIPOCLIENTE   
		WHEN 1 THEN 'CONTRATO'   
		WHEN 2 THEN 'RESERVA'   
		ELSE 'DEPARTAMENTO'  
	END AS TPCLIENTE,  
	RELEFE.CODIGO AS RE_EFETIVO, 
	ENTEFE.NOMECOMPLETO AS NOME_EFETIVO,
	PLANO.NOME AS PLANOREMUNERACAO,
	COALESCE(PARAMETROFERIAS.FTCASH,0) PARAMFERIASFTCASH  
	FROM   RELACAOENTIDADE RELEMPRESA  
		inner join EMPRESA EMPRESAFUNC ON (EMPRESAFUNC.EMPRESA=RELEMPRESA.RELACAOENTIDADE)  
		INNER JOIN ENTIDADE ENTEMPRESA ON (ENTEMPRESA.ENTIDADE=RELEMPRESA.PAPEL1)  
		INNER JOIN RELACAOENTIDADE RELFUNCIONARIO ON (RELFUNCIONARIO.PAPEL2=RELEMPRESA.RELACAOENTIDADE AND RELFUNCIONARIO.SITUACAO=1 AND RELFUNCIONARIO.RELACAO=6)  
		LEFT JOIN PARAMETROFERIAS ON (PARAMETROFERIAS.EMPRESA=RELFUNCIONARIO.PAPEL2)  INNER JOIN ENTIDADE ENTFUNCIONARIO ON (ENTFUNCIONARIO.ENTIDADE=RELFUNCIONARIO.PAPEL1)  
		INNER JOIN FUNCIONARIO FUNCIONARIODIRETO ON (FUNCIONARIODIRETO.FUNCIONARIO=RELFUNCIONARIO.RELACAOENTIDADE)  
		INNER JOIN FUNCIONARIO FUNCIONARIOORIGINAL ON (FUNCIONARIOORIGINAL.FUNCORIGINAL=FUNCIONARIODIRETO.FUNCORIGINAL AND FUNCIONARIOORIGINAL.DTADMISSAO<=FUNCIONARIODIRETO.DTADMISSAO)  
		INNER JOIN PONTO ON (PONTO.COLABORADOR=FUNCIONARIOORIGINAL.FUNCIONARIO 
			AND  PONTO.DATA BETWEEN @DATA_INICIO AND @DATA_FIM  
			and PONTO.SITMOBRAHOJE not IN (12,14) 
			AND (FUNCIONARIODIRETO.DTDEMISSAO IS NULL OR PONTO.DATA<=FUNCIONARIODIRETO.DTDEMISSAO))  
		inner join SITMAODEOBRAFUNC on (SITMAODEOBRAFUNC.FUNCIONARIO=PONTO.COLABORADOR AND SITMAODEOBRAFUNC.DTINICIO<=PONTO.DATA
			AND (SITMAODEOBRAFUNC.DTFIM IS NULL OR SITMAODEOBRAFUNC.DTFIM>=PONTO.DATA) AND SITMAODEOBRAFUNC.SITUACAO=1) 
		INNER JOIN PONTOVAGA ON (PONTOVAGA.PONTOVAGA=PONTO.PONTOVAGA) 
		INNER JOIN TABELAHORARIO ON (TABELAHORARIO.TABELAHORARIO=PONTOVAGA.TABELAHORARIO)  
		OUTER APPLY (  
			SELECT DISTINCT CTR_FALTAABONADA.COLABORADOR 
				FROM CTR_FALTAABONADA  
					WHERE  CTR_FALTAABONADA.COLABORADOR=PONTO.COLABORADOR  
						AND CTR_FALTAABONADA.DTFIM>=PONTO.DATA 
						AND CTR_FALTAABONADA.DTINICIO<=PONTO.DATA  ) as CTR_FALTAABONADA  
		INNER JOIN VAGAITEMCONTRATO ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=PONTOVAGA.VAGAITEMCONTRATOEFETIVO)  
		INNER JOIN LIGAVGITEMCONTRATO LIGAVGEFETIVO ON (LIGAVGEFETIVO.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO 
														AND LIGAVGEFETIVO.DTIMPLANTACAO <= PONTO.DATA 
														AND (LIGAVGEFETIVO.DTENCERRAMENTO >= PONTO.DATA 
														OR LIGAVGEFETIVO.DTENCERRAMENTO IS NULL))  
		INNER JOIN ITENSCONTRLOCAL ITENSCONTRLOCAL_EFETIVO ON (ITENSCONTRLOCAL_EFETIVO.ITENSCONTRLOCAL=LIGAVGEFETIVO.ITENSCONTRLOCAL)  
		INNER JOIN ITENSCONTRATO ITENSCONTRATO_EFETIVO ON (ITENSCONTRATO_EFETIVO.ITENSCONTRATO=ITENSCONTRLOCAL_EFETIVO.ITENSCONTRATO)  
		INNER JOIN VAGAITEMCONTRATO VAGAFOLGUISTA ON (VAGAFOLGUISTA.VAGAITEMCONTRATO=PONTOVAGA.VAGAITEMCONTRATO)  
		INNER JOIN ORIGEMVAGA ON (ORIGEMVAGA.ORIGEMVAGA = VAGAFOLGUISTA.ORIGEMVAGA)  
		INNER JOIN ORIGEMVAGA ORIGEMVAGAEFETIVO ON (ORIGEMVAGAEFETIVO.ORIGEMVAGA=VAGAITEMCONTRATO.ORIGEMVAGA)  
		INNER JOIN LIGAVGITEMCONTRATO    
		INNER JOIN ITENSCONTRLOCAL ON (ITENSCONTRLOCAL.ITENSCONTRLOCAL=LIGAVGITEMCONTRATO.ITENSCONTRLOCAL)   
		INNER JOIN ITENSCONTRATO ON (ITENSCONTRATO.ITENSCONTRATO=ITENSCONTRLOCAL.ITENSCONTRATO)  ON (LIGAVGITEMCONTRATO.VAGAITEMCONTRATO=PONTOVAGA.VAGAITEMCONTRATO 
																										AND LIGAVGITEMCONTRATO.DTIMPLANTACAO <= PONTO.DATA 
																										AND (LIGAVGITEMCONTRATO.DTENCERRAMENTO >= PONTO.DATA 
																										OR LIGAVGITEMCONTRATO.DTENCERRAMENTO IS NULL))  
		INNER JOIN ALOCACAOMAODEOBRA ON (PONTO.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA  
											AND ALOCACAOMAODEOBRA.SITALOCACAO=1 
											AND ALOCACAOMAODEOBRA.DTINICIO<=PONTO.DATA  
											AND ((ALOCACAOMAODEOBRA.DTFIM>=PONTO.DATA) 
											OR (ALOCACAOMAODEOBRA.DTFIM IS NULL)))  
		INNER JOIN VAGAITEMCONTRATO VAGAALOCACAO on (VAGAALOCACAO.VAGAITEMCONTRATO=ALOCACAOMAODEOBRA.VAGAITEMCONTRATO)  
		INNER JOIN CARGOFUNCIONARIOS    
		INNER JOIN CARGO ON (CARGO.CARGO = CARGOFUNCIONARIOS.CARGO)  ON ((CARGOFUNCIONARIOS.FUNCIONARIO=FUNCIONARIOORIGINAL.FUNCIONARIO) 
																				AND CARGOFUNCIONARIOS.DTINICIO <= PONTO.DATA 
																				AND (CARGOFUNCIONARIOS.DTFIM >= PONTO.DATA 
																				OR CARGOFUNCIONARIOS.DTFIM IS NULL))   
		INNER JOIN COMPOSICAOITENSCONTRATO ON (LIGAVGITEMCONTRATO.COMPOSICAOITENSCONTRATO=COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO) 
		INNER JOIN PLANO ON (COMPOSICAOITENSCONTRATO.PLANOREMOPER=PLANO.PLANO)   
		INNER JOIN ESCALATRABALHO ON (ESCALATRABALHO.ESCALATRABALHO=VAGAFOLGUISTA.ESCALATRABALHO) 
		INNER JOIN POSTOLOCALSERVICO ON (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO) 
		INNER JOIN RELACAOENTIDADE RELPOSTOLOCALSERVICO ON (RELPOSTOLOCALSERVICO.RELACAOENTIDADE=POSTOLOCALSERVICO.POSTOSERVICO)  
		INNER JOIN ENTIDADE ENTPOSTOLOCALSERVICO ON (ENTPOSTOLOCALSERVICO.ENTIDADE=RELPOSTOLOCALSERVICO.PAPEL1) 
		INNER JOIN LOCALSERVICOEMP ON (LOCALSERVICOEMP.LOCALSERVICOEMP=POSTOLOCALSERVICO.LOCALSERVICOEMP)  
		INNER JOIN RELACAOENTIDADE RELLOCALSERVICO ON (RELLOCALSERVICO.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)  
		INNER JOIN ENTIDADE ENTLOCALSERVICO ON (ENTLOCALSERVICO.ENTIDADE=RELLOCALSERVICO.PAPEL1)  
		INNER JOIN RELACAOENTIDADE RELCLI ON (RELCLI.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)  
		INNER JOIN ENTIDADE ENTCLI ON (RELCLI.PAPEL1=ENTCLI.ENTIDADE) 
		LEFT JOIN COMPLPONTO COMPLPONTOENTRADA ON (COMPLPONTOENTRADA.PONTO=PONTO.PONTO 
												AND COMPLPONTOENTRADA.SITUACAO=1  
												AND COMPLPONTOENTRADA.TPMOVIMENTO IN (1,2,9))  
		LEFT JOIN COMPLPONTO COMPLPONTOSAIDA ON (COMPLPONTOSAIDA.PONTO=PONTO.PONTO 
													AND COMPLPONTOSAIDA.SITUACAO=1 
													AND COMPLPONTOSAIDA.TPMOVIMENTO IN (6,7,8,10,11))  
		LEFT JOIN COMPLPONTO COMPLPONTOALMOCO ON (COMPLPONTOALMOCO.PONTO=PONTO.PONTO AND COMPLPONTOALMOCO.TPMOVIMENTO=4 AND COMPLPONTOALMOCO.SITUACAO=1)  
		LEFT JOIN COMPLPONTO COMPLPONTOREFCOMPLEMENTAR ON (COMPLPONTOREFCOMPLEMENTAR.PONTO=PONTO.PONTO AND COMPLPONTOREFCOMPLEMENTAR.TPMOVIMENTO=12 AND COMPLPONTOREFCOMPLEMENTAR.SITUACAO=1) 
		INNER JOIN SITUACAOMOBRA  on (SITMAODEOBRAFUNC.SITUACAOMOBRATEMP=SITUACAOMOBRA.SITUACAOMOBRA) 
		INNER JOIN SITMOBRAHOJE ON (PONTO.SITMOBRAHOJE=SITMOBRAHOJE.SITMOBRAHOJE) 
		INNER JOIN ALOCACAOMAODEOBRA ALOCACAOMOEFETIVO ON (ALOCACAOMOEFETIVO.COLABORADOR=PONTO.COLABORADOR 
															AND ALOCACAOMOEFETIVO.SITALOCACAO=1
															AND ALOCACAOMOEFETIVO.TPALOCACAO=1 
															AND ALOCACAOMOEFETIVO.DTINICIO<=PONTO.DATA 
															AND ((ALOCACAOMOEFETIVO.DTFIM >= PONTO.DATA)
															OR (ALOCACAOMOEFETIVO.DTFIM IS NULL)))  
		INNER JOIN VAGAITEMCONTRATO VAGAEFETIVO ON (VAGAEFETIVO.VAGAITEMCONTRATO=ALOCACAOMOEFETIVO.VAGAITEMCONTRATO) 
		inner JOIN CLIENTE CLIENTEEFETIVO ON (VAGAEFETIVO.CLIENTE= CLIENTEEFETIVO.CLIENTE) 
		INNER JOIN CARGO CARGOVAGA ON (CARGOVAGA.CARGO=VAGAITEMCONTRATO.CARGO) 
		INNER JOIN ESCALATRABALHO ESCALATRABALHOVGEFETIVO ON (ESCALATRABALHOVGEFETIVO.ESCALATRABALHO = VAGAEFETIVO.ESCALATRABALHO) 
		LEFT JOIN PARAMFOLHA ON (RELEMPRESA.RELACAOENTIDADE=PARAMFOLHA.EMPRESA) 
		LEFT JOIN MOTMOVIMENTACAO MOTALOC ON (ALOCACAOMAODEOBRA.MOTIVOIMPLANTACAO=MOTALOC.MOTMOVIMENTACAO) 
		inner join ALOCACAOMAODEOBRA ULTIMAALOCACAO  on (ULTIMAALOCACAO.COLABORADOR=FUNCIONARIOORIGINAL.FUNCIONARIO 
															AND ULTIMAALOCACAO.SITALOCACAO=1
															AND ULTIMAALOCACAO.TPALOCACAO=1    
															AND (ULTIMAALOCACAO.DTFIM IS NULL OR ULTIMAALOCACAO.DTFIM>=ULTIMAALOCACAO.DTINICIO)      
															AND ((ULTIMAALOCACAO.DTFIM IS NULL )
															OR (ULTIMAALOCACAO.DTFIM=FUNCIONARIOORIGINAL.DTDEMISSAO
															AND FUNCIONARIOORIGINAL.DTDEMISSAO IS NOT NULL)))     
--NO CASO DO FUNCIONÁRIO ESTAR DEMITIDO E TER FOLGA COMO ULTIMO DIA DE TRABALHO  
		left join SITMOBRAHOJEFUNC SITDEMISSAO ON (SITDEMISSAO.ALOCACAOMAODEOBRA=ULTIMAALOCACAO.ALOCACAOMAODEOBRA 
													AND SITDEMISSAO.DTINICIO=FUNCIONARIODIRETO.DTDEMISSAO 
													AND SITDEMISSAO.DTFIM=SITDEMISSAO.DTINICIO 
													AND SITDEMISSAO.SITUACAO=1 
													AND SITDEMISSAO.SITMOBRAHOJE=12)    
		left join PONTO PONTOULTIMAALOCACAO ON (PONTOULTIMAALOCACAO.COLABORADOR=FUNCIONARIOORIGINAL.FUNCIONARIO
													AND  FUNCIONARIOORIGINAL.DTDEMISSAO IS NOT NULL             
													AND PONTOULTIMAALOCACAO.DATA=FUNCIONARIOORIGINAL.DTDEMISSAO 
													AND PONTOULTIMAALOCACAO.SITMOBRAHOJE=12)  
		INNER JOIN VAGAITEMCONTRATO ULTIMAVAGA ON (ULTIMAVAGA.VAGAITEMCONTRATO=ULTIMAALOCACAO.VAGAITEMCONTRATO)   
		LEFT JOIN LIGAPOSTOLOCALAREASUPER ULTIMOLIGAPOSTOAREASUPER  
		INNER JOIN RELACAOENTIDADE ULTIMORELAREASUPERVISAO ON (ULTIMORELAREASUPERVISAO.RELACAOENTIDADE=ULTIMOLIGAPOSTOAREASUPER.AREASUPERVISAO)     
		INNER JOIN ENTIDADE ULTIMOENTAREASUPERVISAO ON (ULTIMOENTAREASUPERVISAO.ENTIDADE=ULTIMORELAREASUPERVISAO.PAPEL1)  
													ON (ULTIMOLIGAPOSTOAREASUPER.POSTOLOCALSERVICO=ULTIMAVAGA.POSTOLOCALSERVICO 
														AND ULTIMOLIGAPOSTOAREASUPER.TURNOTRABALHO=ULTIMAVAGA.TURNOTRABALHO 
														AND ULTIMOLIGAPOSTOAREASUPER.SITUACAO=1)   
		LEFT JOIN HISTDISCIPLINAR HISTDISCIENT      
		INNER JOIN OCORRENCIADISCIPLINA OCORRENCIAENT	ON (OCORRENCIAENT.OCORRENCIADISCIPLINA=HISTDISCIENT.OCORRENCIADISCIPLINA)  
														ON (HISTDISCIENT.HISTDISCIPLINAR=COMPLPONTOENTRADA.HISTDISCIPLINAR 
															AND HISTDISCIENT.SITUACAO=1 
															and HISTDISCIENT.STATUS=2)    
		LEFT JOIN HISTDISCIPLINAR HISTDISCSAIDA     
		INNER JOIN OCORRENCIADISCIPLINA OCORRENCIASAIDA ON (OCORRENCIASAIDA.OCORRENCIADISCIPLINA=HISTDISCSAIDA.OCORRENCIADISCIPLINA) 
														ON (HISTDISCSAIDA.HISTDISCIPLINAR=COMPLPONTOSAIDA.HISTDISCIPLINAR AND HISTDISCSAIDA.SITUACAO=1 AND HISTDISCSAIDA.STATUS=2)   
		LEFT JOIN RELACAOENTIDADE RELSUP ON RELSUP.RELACAOENTIDADE=LOCALSERVICOEMP.GESTOROPERACIONAL    
		LEFT JOIN LIGAPOSTOLOCALAREASUPER     
		INNER JOIN RELACAOENTIDADE RELAREASUPERVISAO ON (RELAREASUPERVISAO.RELACAOENTIDADE=LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)     
		INNER JOIN ENTIDADE ENTAREASUPERVISAO	ON (ENTAREASUPERVISAO.ENTIDADE=RELAREASUPERVISAO.PAPEL1) 
												ON (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=VAGAITEMCONTRATO.POSTOLOCALSERVICO 
													AND LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO 
													AND LIGAPOSTOLOCALAREASUPER.SITUACAO=1)   
		LEFT JOIN ALOCACAOMAODEOBRA  ALOCACAOEFETIVO   
		INNER JOIN RELACAOENTIDADE RELEFE ON (ALOCACAOEFETIVO.COLABORADOR=RELEFE.RELACAOENTIDADE)  
		INNER JOIN ENTIDADE ENTEFE	ON (RELEFE.PAPEL1=ENTEFE.ENTIDADE)  
									ON (ALOCACAOEFETIVO.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO   
										AND ALOCACAOEFETIVO.TPALOCACAO=1   
										AND ALOCACAOEFETIVO.SITALOCACAO=1  
										AND ALOCACAOEFETIVO.COLABORADOR<>PONTO.COLABORADOR  
										AND ALOCACAOEFETIVO.DTINICIO<=PONTO.DATA   
										AND ((ALOCACAOEFETIVO.DTFIM>=PONTO.DATA) 
										OR ALOCACAOEFETIVO.DTFIM IS NULL))      
			WHERE  
			((SITDEMISSAO.SITMOBRAHOJE IS NULL) 
			OR (SITDEMISSAO.SITMOBRAHOJE IS NOT NULL 
			AND (PONTOULTIMAALOCACAO.PONTO IS NULL OR PONTO.PONTO<>COALESCE(PONTOULTIMAALOCACAO.PONTO, 0))))
	AND (ALOCACAOMAODEOBRA.TPCOBERTURA = 2 OR ORIGEMVAGAEFETIVO.DESCRICAO IN ('EXCEDENTE','TREINAMENTO'))
