DECLARE @DATA_ATUAL DATE = CAST(GETDATE() AS DATE);

WITH CTR_RELACAOENTIDADE AS  
	(select  RELACAOENTIDADE.RELACAOENTIDADE
		,RELACAOENTIDADE.PAPEL2
		,RELACAOENTIDADE.CODIGO
		,ENTIDADE.NOMECOMPLETO
		,ENTIDADE.NOMERESUMIDO
		,RELACAOENTIDADE.CENTROCUSTO  
			from RELACAOENTIDADE WITH (NOLOCK) INNER JOIN ENTIDADE WITH (NOLOCK) ON (ENTIDADE.ENTIDADE=RELACAOENTIDADE.PAPEL1))
	,CTR_EXTRATCONT AS (  
		SELECT  ITENSCONTRLOCAL.ITENSCONTRLOCAL
			,EXTRACONTITENSCOMP.TURNOTRABALHO
			,SUM(EXTRACONTITENSCOMP.VALORMENSAL) VALORMENSAL
			,SUM(EXTRACONTITENSCOMP.VALORLIQUIDOMENSAL) VALORLIQUIDOMENSAL
			,SUM(EXTRACONTITENSCOMP.RESULTADO) RESULTADO
			,SUM(EXTRACONTITENSCOMP.VALORTOTALCUSTO) VALORTOTALCUSTO  
				FROM EXTRACONTITENSCOMP WITH (NOLOCK) INNER JOIN ITENSCONTRLOCAL WITH (NOLOCK) on (ITENSCONTRLOCAL.ITENSCONTRLOCAL=EXTRACONTITENSCOMP.ITENSCONTRLOCAL)  
					INNER JOIN RELACAOENTIDADE RELLOC WITH (NOLOCK) on (RELLOC.RELACAOENTIDADE=ITENSCONTRLOCAL.LOCALSERVICO)  
					INNER JOIN ITENSCONTRATO WITH (NOLOCK) ON (ITENSCONTRATO.ITENSCONTRATO=ITENSCONTRLOCAL.ITENSCONTRATO AND ITENSCONTRATO.SITUACAO=1)  
					INNER JOIN VERSAOCONTRATO WITH (NOLOCK) ON (
						VERSAOCONTRATO.VERSAOCONTRATO=ITENSCONTRATO.VERSAOCONTRATO AND VERSAOCONTRATO.SITUACAOCONTR IN (3,4))  
					INNER JOIN CONTRATO WITH (NOLOCK) ON (CONTRATO.CONTRATO=VERSAOCONTRATO.CONTRATO)  
					INNER JOIN RELACAOENTIDADE RELCONTRATO WITH (NOLOCK) ON (RELCONTRATO.RELACAOENTIDADE=VERSAOCONTRATO.CONTRATO)  
					INNER JOIN CLIENTE WITH (NOLOCK) ON (CLIENTE.CLIENTE=RELCONTRATO.PAPEL2 AND CLIENTE.TIPOCLIENTE<>3)  
							where  (ITENSCONTRLOCAL.DTIMPLANTACAO<=@DATA_ATUAL)  
								AND (ITENSCONTRLOCAL.DTENCERRAMENTO>= @DATA_ATUAL OR ITENSCONTRLOCAL.DTENCERRAMENTO IS NULL) 
								GROUP BY ITENSCONTRLOCAL.ITENSCONTRLOCAL, EXTRACONTITENSCOMP.TURNOTRABALHO  )
	,CTR_VAGASREFORCOS AS 
		(select  LIGAVGITEMCONTRATO.ITENSCONTRLOCAL
			,COUNT(VAGAITEMCONTRATO.VAGAITEMCONTRATO) QTDE  
				from VAGAITEMCONTRATO WITH (NOLOCK) INNER JOIN CONTRATO WITH (NOLOCK) ON (CONTRATO.CONTRATO=VAGAITEMCONTRATO.CONTRATO)  
					INNER JOIN CLIENTE WITH (NOLOCK) ON (CLIENTE.CLIENTE=VAGAITEMCONTRATO.CLIENTE AND CLIENTE.TIPOCLIENTE<>3)  
					INNER JOIN RELACAOENTIDADE RELLOC WITH (NOLOCK) on (RELLOC.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)  
					INNER JOIN LIGAVGITEMCONTRATO WITH (NOLOCK) ON (LIGAVGITEMCONTRATO.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)  
						WHERE  VAGAITEMCONTRATO.TPVAGA=1 
							AND VAGAITEMCONTRATO.ORIGEMVAGA IN (6,7)  
							AND VAGAITEMCONTRATO.DTIMPLANTACAO<=@DATA_ATUAL
							AND (VAGAITEMCONTRATO.DTENCERRAMENTO IS NULL OR VAGAITEMCONTRATO.DTENCERRAMENTO>=@DATA_ATUAL )  
							AND LIGAVGITEMCONTRATO.DTIMPLANTACAO<=@DATA_ATUAL 
							AND (LIGAVGITEMCONTRATO.DTENCERRAMENTO IS NULL OR LIGAVGITEMCONTRATO.DTENCERRAMENTO>=@DATA_ATUAL)  
							GROUP BY  LIGAVGITEMCONTRATO.ITENSCONTRLOCAL)
	,CTR_VAGASEFETIVAS AS 
		(select  LIGAVGITEMCONTRATO.ITENSCONTRLOCAL
			,COUNT(VAGAITEMCONTRATO.VAGAITEMCONTRATO) QTDE  
				from VAGAITEMCONTRATO WITH (NOLOCK) INNER JOIN CONTRATO WITH (NOLOCK) ON (CONTRATO.CONTRATO=VAGAITEMCONTRATO.CONTRATO)  
					INNER JOIN CLIENTE WITH (NOLOCK) ON (CLIENTE.CLIENTE=VAGAITEMCONTRATO.CLIENTE AND CLIENTE.TIPOCLIENTE<>3)  
					INNER JOIN RELACAOENTIDADE RELLOC WITH (NOLOCK) on (RELLOC.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)  
					INNER JOIN LIGAVGITEMCONTRATO WITH (NOLOCK) ON (LIGAVGITEMCONTRATO.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)  
						WHERE  VAGAITEMCONTRATO.TPVAGA=1 
							AND VAGAITEMCONTRATO.ORIGEMVAGA=1  
							AND VAGAITEMCONTRATO.DTIMPLANTACAO<=@DATA_ATUAL
							AND (VAGAITEMCONTRATO.DTENCERRAMENTO IS NULL OR VAGAITEMCONTRATO.DTENCERRAMENTO>=@DATA_ATUAL )  
							AND LIGAVGITEMCONTRATO.DTIMPLANTACAO<=@DATA_ATUAL
							AND (LIGAVGITEMCONTRATO.DTENCERRAMENTO IS NULL OR LIGAVGITEMCONTRATO.DTENCERRAMENTO>=@DATA_ATUAL )  
							GROUP BY  LIGAVGITEMCONTRATO.ITENSCONTRLOCAL)
	,CTR_ALOCACOESEFETIVAS AS 
		(select  LIGAVGITEMCONTRATO.ITENSCONTRLOCAL
			,COUNT(VAGAITEMCONTRATO.VAGAITEMCONTRATO) QTDE  
				from VAGAITEMCONTRATO WITH (NOLOCK) INNER JOIN CONTRATO WITH (NOLOCK) ON (CONTRATO.CONTRATO=VAGAITEMCONTRATO.CONTRATO)  
					INNER JOIN CLIENTE WITH (NOLOCK) ON (CLIENTE.CLIENTE=VAGAITEMCONTRATO.CLIENTE AND CLIENTE.TIPOCLIENTE<>3)  
					INNER JOIN RELACAOENTIDADE RELLOC WITH (NOLOCK) ON (RELLOC.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)  
					INNER JOIN LIGAVGITEMCONTRATO WITH (NOLOCK) ON (LIGAVGITEMCONTRATO.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)  
					INNER JOIN ALOCACAOMAODEOBRA WITH (NOLOCK) ON (ALOCACAOMAODEOBRA.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO 
						AND ALOCACAOMAODEOBRA.SITALOCACAO=1 AND ALOCACAOMAODEOBRA.TPALOCACAO=1           
						AND ALOCACAOMAODEOBRA.DTINICIO<=@DATA_ATUAL                                
						AND (ALOCACAOMAODEOBRA.DTFIM IS NULL OR ALOCACAOMAODEOBRA.DTFIM>=@DATA_ATUAL ))  
						WHERE  VAGAITEMCONTRATO.TPVAGA=1 
							AND VAGAITEMCONTRATO.ORIGEMVAGA=1  
							AND VAGAITEMCONTRATO.DTIMPLANTACAO<=@DATA_ATUAL 
							AND (VAGAITEMCONTRATO.DTENCERRAMENTO IS NULL OR VAGAITEMCONTRATO.DTENCERRAMENTO>=@DATA_ATUAL )  
							AND LIGAVGITEMCONTRATO.DTIMPLANTACAO<=@DATA_ATUAL 
							AND (LIGAVGITEMCONTRATO.DTENCERRAMENTO IS NULL OR LIGAVGITEMCONTRATO.DTENCERRAMENTO>=@DATA_ATUAL )   
							GROUP BY  LIGAVGITEMCONTRATO.ITENSCONTRLOCAL  ) 
SELECT  
	 DADOS.EMPRESA
	,DADOS.CODIGOCCRESUMIDO
	,DADOS.CENTROCUSTO
	,DADOS.EQUIPEVENDAS
	,DADOS.NOMEVENDEDOR
	,DADOS.NOMECLIENTE
	,DADOS.NOMEFANTASIA
	,DADOS.LOCALSERVICO
	,DADOS.DESCRICAOFISCAL
	,CASE 
		WHEN DADOS.DESCRICAOFISCAL LIKE '%Noturno%' THEN 'Noturno'
		ELSE 'Diurno'
	END AS 'Turno'
	,DADOS.DESCRICAO_CARGO CARGO
	,DADOS.DESCRICAO_ESCALA ESCALA
	,CASE	
		WHEN DADOS.DESCRICAO_CARGO LIKE '%PARCIAL%'	THEN 'Almocista'
		ELSE 'Efetivo'
	END AS TIPOVAGA
	,DADOS.DESCRICAO_JORNADA JORNADA
	,SUM(ROUND(DADOS.VALORMENSAL,2)) AS VALORMENSAL
	,SUM(ROUND(DADOS.VALORLIQUIDOMENSAL,2)) AS VALORLIQUIDOMENSAL
	,SUM(ROUND(DADOS.RESULTADO,2)) AS RESULTADO
	,SUM(ROUND(DADOS.BASECALCULORESULT,2)) AS BASECALCULORESULT
	,DADOS.VENDIDOS
	,DADOS.QTDEPOSTOS
	,DADOS.QTDECORTESIA
	,SUM(DADOS.QTDEEFETIVO) AS QTDEEFETIVO
	,SUM(DADOS.QTDEREFORCO) AS QTDEREFORCO
	,SUM(DADOS.QTDEIMPLANTADOS) AS QTDEIMPLANTADOS
	,CASE DADOS.TPRESULTADO      
		WHEN 1 THEN 'VALOR MENSAL BRUTO'      
		WHEN 2 THEN 'VALOR MENSAL LIQUIDO'      
		WHEN 3 THEN 'TOTAL DE CUSTO'  
	END AS TPRESULTADO  
		FROM (SELECT	RELEMP.NOMERESUMIDO EMPRESA
						,RELCON.CODIGO CONTRATO
						,VERSAOCONTRATO.SEQCONTRATO VERSAO
						,CENTROCUSTO.CODIGOCCRESUMIDO
						,CENTROCUSTO.DESCRICAO CENTROCUSTO
						,COALESCE(RELEQP.NOMECOMPLETO, 'SEM EQUIPE') AS EQUIPEVENDAS
						,COALESCE(RELVEN.NOMECOMPLETO, 'SEM VENDEDOR') AS NOMEVENDEDOR
						,RELCLI.NOMECOMPLETO NOMECLIENTE
						,RELCLI.NOMERESUMIDO NOMEFANTASIA
						,RELLOC.NOMERESUMIDO AS LOCALSERVICO
						,ITENSCONTRATO.ITENSCONTRATO
						,CASE      
							WHEN COMPOSICAOITENSCONTRATO.TPQUANTIDADE IN (1,3) THEN COMPOSICAOITENSCONTRATO.QTDE      
							WHEN COMPOSICAOITENSCONTRATO.TPQUANTIDADE IN (2,5) THEN COMPOSICAOITENSCONTRATO.QTDE*          
							(CASE ITENSCONTRATO.TPITENSCONTRATO                  
								WHEN 1 THEN ITENSCONTRLOCAL.QTDE             
								WHEN 2 THEN 0          
							END)  
						END QTDEPOSTOS
						,CASE      
							WHEN COMPOSICAOITENSCONTRATO.TPQUANTIDADE IN (1,3) THEN COMPOSICAOITENSCONTRATO.QTDE      
							WHEN COMPOSICAOITENSCONTRATO.TPQUANTIDADE IN (2,5) THEN COMPOSICAOITENSCONTRATO.QTDE*      
							(CASE ITENSCONTRATO.TPITENSCONTRATO          
								WHEN 1 THEN 0          
								WHEN 2 THEN ITENSCONTRLOCAL.QTDE     
							END)  
						END QTDECORTESIA,    
						CASE 
							WHEN COMPOSICAOITENSCONTRATO.TPQUANTIDADE IN (1,3) THEN COMPOSICAOITENSCONTRATO.QTDE*
								COALESCE(ESCALATRABALHO.MULTIPLOVAGA,NULL,1)      
							WHEN COMPOSICAOITENSCONTRATO.TPQUANTIDADE IN (2,5) THEN COMPOSICAOITENSCONTRATO.QTDE*
								COALESCE(ESCALATRABALHO.MULTIPLOVAGA,NULL,1)*      
								(CASE ITENSCONTRATO.TPITENSCONTRATO          
									WHEN 1 THEN ITENSCONTRLOCAL.QTDE          
									WHEN 2 THEN 0      
								END) 
						END VENDIDOS
						,COMPOSICAOITENSCONTRATO.ALOCACAO JORNADA
						,JORNADA.DESCRICAO DESCRICAO_JORNADA
						,ESCALATRABALHO.ESCALATRABALHO
						,ESCALATRABALHO.DESCRICAO DESCRICAO_ESCALA
						,ITENSCONTRATO.DESCRICAOFISCAL
						,ITENSCONTRLOCAL.ITENSCONTRLOCAL
						,CTR_EXTRATCONT.VALORMENSAL
						,CTR_EXTRATCONT.VALORLIQUIDOMENSAL
						,CTR_EXTRATCONT.RESULTADO
						,PARAMETROORCAMENTO.TPRESULTADO,
						CASE PARAMETROORCAMENTO.TPRESULTADO      
							WHEN 1 THEN CTR_EXTRATCONT.VALORMENSAL      
							WHEN 2 THEN CTR_EXTRATCONT.VALORLIQUIDOMENSAL      
							WHEN 3 THEN CTR_EXTRATCONT.VALORTOTALCUSTO  
						END AS BASECALCULORESULT
						,COALESCE(CTR_VAGASEFETIVAS.QTDE,0) QTDEEFETIVO
						,COALESCE(CTR_VAGASREFORCOS.QTDE,0) QTDEREFORCO
						,COALESCE(CTR_ALOCACOESEFETIVAS.QTDE,0) QTDEIMPLANTADOS
						,CTR_EXTRATCONT.TURNOTRABALHO
						,CARGO.DESCRICAO DESCRICAO_CARGO
						,COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO  
							FROM CLIENTE WITH (NOLOCK) INNER JOIN CTR_RELACAOENTIDADE RELCLI WITH (NOLOCK) ON (RELCLI.RELACAOENTIDADE=CLIENTE.CLIENTE)  
								INNER JOIN CTR_RELACAOENTIDADE RELCON WITH (NOLOCK) ON (RELCON.PAPEL2=CLIENTE.CLIENTE)  
								INNER JOIN CONTRATO WITH (NOLOCK) ON (RELCON.RELACAOENTIDADE = CONTRATO.CONTRATO)  
								INNER JOIN VERSAOCONTRATO WITH (NOLOCK) ON (CONTRATO.CONTRATO = VERSAOCONTRATO.CONTRATO)  
								LEFT JOIN VERSAOCONTRATO VERSAOANT WITH (NOLOCK) ON 
									(VERSAOANT.VERCONTRANT=VERSAOCONTRATO.VERSAOCONTRATO AND VERSAOANT.SITUACAOCONTR IN (3,4))  
								INNER JOIN NEGOCIACAO WITH (NOLOCK) ON (VERSAOCONTRATO.NEGOCIACAO = NEGOCIACAO.NEGOCIACAO)  
								LEFT JOIN CTR_RELACAOENTIDADE RELVEN WITH (NOLOCK) ON (NEGOCIACAO.VENDEDOR = RELVEN.RELACAOENTIDADE)  
								LEFT JOIN CTR_RELACAOENTIDADE RELEQP WITH (NOLOCK) ON (RELEQP.RELACAOENTIDADE=CLIENTE.EQUIPEVENDAS)  
								INNER JOIN ITENSCONTRATO WITH (NOLOCK) ON (VERSAOCONTRATO.VERSAOCONTRATO = ITENSCONTRATO.VERSAOCONTRATO and ITENSCONTRATO.SITUACAO=1)  
								INNER JOIN COMPOSICAOITENSCONTRATO WITH (NOLOCK) ON 
									(ITENSCONTRATO.ITENSCONTRATO=COMPOSICAOITENSCONTRATO.ITENSCONTRATO 
										AND COMPOSICAOITENSCONTRATO.SITUACAO=1 
										AND COMPOSICAOITENSCONTRATO.ORIGEMCOMPOSICAOITENSCONTRATO=1)  
								INNER JOIN CARGOEMPRESA WITH (NOLOCK) ON (CARGOEMPRESA.CARGOEMPRESA=COMPOSICAOITENSCONTRATO.CARGOEMPRESA)  
								INNER JOIN CARGO WITH (NOLOCK) ON (CARGO.CARGO=CARGOEMPRESA.CARGO)  
								INNER JOIN ESCALATRABALHO WITH (NOLOCK) ON (ESCALATRABALHO.ESCALATRABALHO=COMPOSICAOITENSCONTRATO.ESCALATRABALHO) 
								INNER JOIN ALOCACAO JORNADA WITH (NOLOCK) ON (JORNADA.ALOCACAO=COMPOSICAOITENSCONTRATO.ALOCACAO)  
								INNER JOIN ITENSCONTRLOCAL WITH (NOLOCK) ON (ITENSCONTRATO.ITENSCONTRATO=ITENSCONTRLOCAL.ITENSCONTRATO) 
								INNER JOIN LOCALSERVICO WITH (NOLOCK) ON (ITENSCONTRLOCAL.LOCALSERVICO=LOCALSERVICO.LOCALSERVICO)  
								INNER JOIN CTR_RELACAOENTIDADE RELLOC WITH (NOLOCK) ON 
									(RELLOC.RELACAOENTIDADE=LOCALSERVICO.LOCALSERVICO
										AND RELCLI.RELACAOENTIDADE=RELLOC.PAPEL2)  
								LEFT JOIN CENTROCUSTO WITH (NOLOCK) ON (CENTROCUSTO.CENTROCUSTO=RELLOC.CENTROCUSTO)  
								INNER JOIN PRODUTOEMPRESA WITH (NOLOCK) ON (ITENSCONTRATO.PRODUTOEMPRESA=PRODUTOEMPRESA.PRODUTOEMPRESA)  
								INNER JOIN PRODUTO WITH (NOLOCK) ON (PRODUTOEMPRESA.PRODUTO = PRODUTO.PRODUTO)  
								INNER JOIN CTR_RELACAOENTIDADE RELEMP WITH (NOLOCK) ON (RELEMP.RELACAOENTIDADE=CONTRATO.EMPRESA)  
								INNER JOIN CTR_EXTRATCONT WITH (NOLOCK) ON 
									(ITENSCONTRLOCAL.ITENSCONTRLOCAL = CTR_EXTRATCONT.ITENSCONTRLOCAL 
										AND CTR_EXTRATCONT.TURNOTRABALHO=COMPOSICAOITENSCONTRATO.TURNOTRABALHO)  
								LEFT JOIN CTR_VAGASEFETIVAS WITH (NOLOCK) ON (CTR_VAGASEFETIVAS.ITENSCONTRLOCAL=ITENSCONTRLOCAL.ITENSCONTRLOCAL)  
								LEFT JOIN CTR_VAGASREFORCOS WITH (NOLOCK) ON (CTR_VAGASREFORCOS.ITENSCONTRLOCAL=ITENSCONTRLOCAL.ITENSCONTRLOCAL)  
								LEFT JOIN CTR_ALOCACOESEFETIVAS WITH (NOLOCK) ON (CTR_ALOCACOESEFETIVAS.ITENSCONTRLOCAL=ITENSCONTRLOCAL.ITENSCONTRLOCAL)  
								INNER JOIN PARAMETROORCAMENTO WITH (NOLOCK) ON (PARAMETROORCAMENTO.PARAMETROORCAMENTO=20)  

									WHERE   VERSAOCONTRATO.SITUACAOCONTR IN (3,4)  
										AND CLIENTE.TIPOCLIENTE<>3  
										AND (ITENSCONTRLOCAL.DTIMPLANTACAO<=@DATA_ATUAL)  
										AND (ITENSCONTRLOCAL.DTENCERRAMENTO>=@DATA_ATUAL OR ITENSCONTRLOCAL.DTENCERRAMENTO IS NULL)  
										AND NOT (
											RELCLI.NOMERESUMIDO = 'FUNDACAO BUTANTAN'
											AND RELEMP.NOMERESUMIDO = 'PRESSSEG SEGURANÇA'
											AND ITENSCONTRATO.DESCRICAOFISCAL like '%RECEPCIONISTA%'										
										)
										AND RELLOC.NOMERESUMIDO NOT LIKE '%TREINAMENTO%'
														 
											GROUP BY	RELEMP.NOMERESUMIDO
														,RELCON.CODIGO
														,VERSAOCONTRATO.SEQCONTRATO
														,CENTROCUSTO.CODIGOCCRESUMIDO
														,CENTROCUSTO.DESCRICAO
														,RELEQP.NOMECOMPLETO
														,RELVEN.NOMECOMPLETO
														,RELCLI.NOMECOMPLETO
														,RELCLI.NOMERESUMIDO
														,RELLOC.NOMERESUMIDO
														,ITENSCONTRATO.ITENSCONTRATO
														,ITENSCONTRATO.TPITENSCONTRATO
														,ITENSCONTRATO.TPITENSCONTRATO
														,ITENSCONTRATO.DESCRICAOFISCAL
														,ITENSCONTRLOCAL.ITENSCONTRLOCAL
														,CTR_EXTRATCONT.VALORMENSAL
														,CTR_EXTRATCONT.VALORLIQUIDOMENSAL
														,CTR_EXTRATCONT.RESULTADO
														,CTR_EXTRATCONT.VALORTOTALCUSTO
														,ITENSCONTRLOCAL.QTDE
														,PARAMETROORCAMENTO.TPRESULTADO
														,CTR_EXTRATCONT.TURNOTRABALHO
														,CTR_VAGASEFETIVAS.QTDE
														,CTR_VAGASREFORCOS.QTDE
														,CTR_ALOCACOESEFETIVAS.QTDE
														,COMPOSICAOITENSCONTRATO.TPQUANTIDADE
														,COMPOSICAOITENSCONTRATO.QTDE
														,ESCALATRABALHO.MULTIPLOVAGA
														,ESCALATRABALHO.ESCALATRABALHO
														,ESCALATRABALHO.DESCRICAO
														,COMPOSICAOITENSCONTRATO.ALOCACAO
														,JORNADA.DESCRICAO 
														,CARGO.CARGO
														,CARGO.DESCRICAO
														,COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO 
				) AS DADOS	
					GROUP BY	 DADOS.EMPRESA
								,DADOS.CODIGOCCRESUMIDO
								,DADOS.CENTROCUSTO
								,DADOS.EQUIPEVENDAS
								,DADOS.NOMEVENDEDOR
								,DADOS.NOMECLIENTE
								,DADOS.NOMEFANTASIA
								,DADOS.LOCALSERVICO
								,DADOS.DESCRICAOFISCAL
								,DADOS.DESCRICAO_CARGO
								,DADOS.DESCRICAO_ESCALA
								,DADOS.DESCRICAO_JORNADA
								,DADOS.TPRESULTADO
								,DADOS.VENDIDOS
								,DADOS.QTDEPOSTOS
								,DADOS.QTDECORTESIA
								,DADOS.COMPOSICAOITENSCONTRATO 
									ORDER BY	 DADOS.NOMECLIENTE
												,DADOS.LOCALSERVICO
												,DADOS.CODIGOCCRESUMIDO
												,DADOS.CENTROCUSTO
												,DADOS.EMPRESA
												,DADOS.EQUIPEVENDAS
												,DADOS.NOMEVENDEDOR
												,DADOS.DESCRICAO_CARGO
												,DADOS.DESCRICAO_ESCALA
												,DADOS.DESCRICAO_JORNADA