-- Quadro Operacional — aba "Reserva" (RS).
-- Lista por pessoa alocada no cliente RESERVA TÉCNICA, classificada em TipoReserva
-- (Reserva / Afastamento / Intermitente / Abandono / Falta Fixa). Foto do dia.
SELECT
	ENTEMPRESA.NOMERESUMIDO EMPRESA,
	ENTBASEOP.NOMECOMPLETO BASEOPERACIONAL,
	ENTCLIENTE.NOMERESUMIDO CLIENTE,
	ENTLOCAL.NOMERESUMIDO LOCALSERVICO,
	CASE
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%AFASTAMENTO%'		THEN 'Afastamento'
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%INTERMITENTE%'	THEN 'Intermitente'
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%ABANDONO%'		THEN 'Abandono'
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%FALTANTE%'		THEN 'Falta Fixa'
		ELSE 'Reserva'
	END AS 'TipoReserva',
	RELFUNC.CODIGO RE,
	ENTFUNC.NOMECOMPLETO FUNCIONARIO,
	TURNOTRABALHO.DESCRICAO TURNO,
	ORIGEMVAGA.DESCRICAO TIPO,
	CARGOVAGA.DESCRICAO CARGO_VAGA,
	CARGO.DESCRICAO CARGO,
	ESCALATRABALHO.SIGLA ESCALA,
	ALOCACAO.DESCRICAO JORNADA,
	FUNCIONARIO.DTADMISSAOORIGINAL DTADMISSAO,
	ALOCACAOMAODEOBRA.DTINICIO DTIMPLANTACAO,
	ALOCACAOMAODEOBRA.DTFIM DTENCERRAMENTO,
	MOTMOVIMENTACAO.DESCRICAO MOTIVO,
	ENTUSUARIO.NOMERESUMIDO  USUARIO,
	CAST(NULL AS VARCHAR(60)) AREALOCALSERVICO,
	ENTAREA.NOMECOMPLETO AREASUPERVISAO,
	CASE SITMOBRAHOJE.SITMOBRAHOJE
		WHEN 1 THEN 'EFETIVO'
		ELSE SITMOBRAHOJE.DESCRICAO
	END SITMOBRAHOJE,
	PLANOOPER.NOME as NOMEPLANOOPER
		FROM ALOCACAOMAODEOBRA WITH (NOLOCK) INNER JOIN SITMOBRAHOJE WITH (NOLOCK) ON (ALOCACAOMAODEOBRA.TPCOBERTURA=SITMOBRAHOJE.SITMOBRAHOJE)
			INNER JOIN VAGAITEMCONTRATO WITH (NOLOCK) ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=ALOCACAOMAODEOBRA.VAGAITEMCONTRATO
												AND ALOCACAOMAODEOBRA.DTINICIO <= CAST(GETDATE() AS DATE)
												AND (ALOCACAOMAODEOBRA.DTFIM >= CAST(GETDATE() AS DATE)
												OR ALOCACAOMAODEOBRA.DTFIM IS NULL))
			INNER JOIN CARGO CARGOVAGA WITH (NOLOCK) ON (CARGOVAGA.CARGO=VAGAITEMCONTRATO.CARGO)
			inner join LIGAVGITEMCONTRATO WITH (NOLOCK) ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=LIGAVGITEMCONTRATO.VAGAITEMCONTRATO
											AND LIGAVGITEMCONTRATO.DTIMPLANTACAO<= CAST(GETDATE() AS DATE)
											AND (LIGAVGITEMCONTRATO.DTENCERRAMENTO >= CAST(GETDATE() AS DATE)
											OR LIGAVGITEMCONTRATO.DTENCERRAMENTO IS NULL))
			inner join COMPOSICAOITENSCONTRATO WITH (NOLOCK) on (LIGAVGITEMCONTRATO.COMPOSICAOITENSCONTRATO=COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO)
			inner join PLANO PLANOOPER WITH (NOLOCK) on (COMPOSICAOITENSCONTRATO.PLANOREMOPER=PLANOOPER.PLANO)
			inner join ORIGEMVAGA WITH (NOLOCK) ON (VAGAITEMCONTRATO.ORIGEMVAGA=ORIGEMVAGA.ORIGEMVAGA)
			inner join FUNCIONARIO WITH (NOLOCK) ON (ALOCACAOMAODEOBRA.COLABORADOR=FUNCIONARIO.FUNCIONARIO)
			INNER JOIN RELACAOENTIDADE RELFUNC WITH (NOLOCK) ON (FUNCIONARIO.FUNCIONARIO=RELFUNC.RELACAOENTIDADE and RELFUNC.SITUACAO=1)
			INNER JOIN ENTIDADE ENTFUNC WITH (NOLOCK) ON (RELFUNC.PAPEL1=ENTFUNC.ENTIDADE)
			INNER JOIN TURNOTRABALHO WITH (NOLOCK) ON (VAGAITEMCONTRATO.TURNOTRABALHO=TURNOTRABALHO.TURNOTRABALHO)
			INNER JOIN CARGOFUNCIONARIOS WITH (NOLOCK) ON (FUNCIONARIO.FUNCIONARIO=CARGOFUNCIONARIOS.FUNCIONARIO
									AND CARGOFUNCIONARIOS.DTINICIO<=CAST(GETDATE() AS DATE)
									AND (CARGOFUNCIONARIOS.DTFIM >= CAST(GETDATE() AS DATE)
										OR CARGOFUNCIONARIOS.DTFIM IS NULL))
			INNER JOIN CARGO WITH (NOLOCK) ON (CARGOFUNCIONARIOS.CARGO=CARGO.CARGO AND CARGO.SITUACAO=1)
			INNER JOIN RELACAOENTIDADE RELUSUARIO WITH (NOLOCK) ON (ALOCACAOMAODEOBRA.USUARIOIMPLANTACAO=RELUSUARIO.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTUSUARIO WITH (NOLOCK) ON (RELUSUARIO.PAPEL1=ENTUSUARIO.ENTIDADE)
			INNER JOIN ESCALATRABALHO WITH (NOLOCK) ON (ESCALATRABALHO.ESCALATRABALHO=VAGAITEMCONTRATO.ESCALATRABALHO)
			INNER JOIN LIGAVGHORARIOOP WITH (NOLOCK) ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=LIGAVGHORARIOOP.VAGAITEMCONTRATO
												AND LIGAVGHORARIOOP.DTIMPLANTACAO<=CAST(GETDATE() AS DATE)
												AND (LIGAVGHORARIOOP.DTENCERRAMENTO>=CAST(GETDATE() AS DATE)
													OR LIGAVGHORARIOOP.DTENCERRAMENTO IS NULL))
			INNER JOIN ALOCACAO WITH (NOLOCK) ON (LIGAVGHORARIOOP.ALOCACAO=ALOCACAO.ALOCACAO)
			INNER JOIN MOTMOVIMENTACAO WITH (NOLOCK) ON (ALOCACAOMAODEOBRA.MOTIVOIMPLANTACAO=MOTMOVIMENTACAO.MOTMOVIMENTACAO)
			INNER JOIN POSTOLOCALSERVICO WITH (NOLOCK) ON (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO)
			INNER JOIN LOCALSERVICOEMP WITH (NOLOCK) ON (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)
			INNER JOIN RELACAOENTIDADE RELEMPRESA WITH (NOLOCK) ON (RELEMPRESA.RELACAOENTIDADE=VAGAITEMCONTRATO.EMPRESA AND RELEMPRESA.SITUACAO=1)
			INNER JOIN ENTIDADE ENTEMPRESA WITH (NOLOCK) ON (RELEMPRESA.PAPEL1=ENTEMPRESA.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELLOCAL WITH (NOLOCK) ON (RELLOCAL.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)
			INNER JOIN ENTIDADE ENTLOCAL WITH (NOLOCK) ON (RELLOCAL.PAPEL1=ENTLOCAL.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELBASEOP WITH (NOLOCK) ON (RELBASEOP.RELACAOENTIDADE=VAGAITEMCONTRATO.BASEOPERACIONAL)
			INNER JOIN ENTIDADE ENTBASEOP WITH (NOLOCK) ON (RELBASEOP.PAPEL1=ENTBASEOP.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELCLIENTE WITH (NOLOCK) ON (RELCLIENTE.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)
			INNER JOIN ENTIDADE ENTCLIENTE WITH (NOLOCK) ON (RELCLIENTE.PAPEL1=ENTCLIENTE.ENTIDADE)
			INNER JOIN CLIENTE TABCLIENTE WITH (NOLOCK) ON (TABCLIENTE.CLIENTE = RELCLIENTE.RELACAOENTIDADE)
			left join LIGAPOSTOLOCALAREASUPER WITH (NOLOCK) left join RELACAOENTIDADE RELAREA WITH (NOLOCK) on (RELAREA.RELACAOENTIDADE =  LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)
			left join ENTIDADE ENTAREA WITH (NOLOCK)	on (ENTAREA.ENTIDADE = RELAREA.PAPEL1)
										on (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=VAGAITEMCONTRATO.POSTOLOCALSERVICO
											and LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO
											and LIGAPOSTOLOCALAREASUPER.SITUACAO=1)
					WHERE
						VAGAITEMCONTRATO.TPVAGA=1
						AND ALOCACAOMAODEOBRA.SITALOCACAO=1
						AND ENTCLIENTE.NOMERESUMIDO = 'RESERVA TÉCNICA'
						AND ENTLOCAL.NOMERESUMIDO NOT IN ('RESERVA - PC', 'RESERVA - PELLEGRINA - CAMPINAS',
															'RESERVA - PELLEGRINA - SÃO PAULO', 'RESERVA PROCESSO CRIMINAL',
																'RESERVAS - TRATATIVAS')
						ORDER BY
							ENTEMPRESA.NOMERESUMIDO,
							ENTBASEOP.NOMECOMPLETO,
							ENTCLIENTE.NOMERESUMIDO,
							ENTLOCAL.NOMECOMPLETO,
							ENTAREA.NOMECOMPLETO,
							RELFUNC.CODIGO;