-- Quadro Operacional — aba "Reserva" (RS).
-- Lista por pessoa alocada no cliente RESERVA TÉCNICA, classificada em TipoReserva
-- (Reserva / Afastamento / Intermitente / Abandono / Falta Fixa). Foto do dia.
SELECT
	ENTEMPRESA.NOMERESUMIDO EMPRESA,
	ENTBASEOP.NOMECOMPLETO BASEOPERACIONAL,
	ENTCLIENTE.NOMERESUMIDO CLIENTE,
	ENTLOCAL.NOMERESUMIDO LOCALSERVICO,
	CASE
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%AFASTAMENTO%'		THEN 'Afastamento'
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%INTERMITENTE%'	THEN 'Intermitente'
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%ABANDONO%'		THEN 'Abandono'
		WHEN ENTLOCAL.NOMERESUMIDO LIKE '%FALTANTE%'		THEN 'Falta Fixa'
		ELSE 'Reserva'
	END AS 'TipoReserva',
	RELFUNC.CODIGO RE,
	ENTFUNC.NOMECOMPLETO FUNCIONARIO,
	TURNOTRABALHO.DESCRICAO TURNO,
	ORIGEMVAGA.DESCRICAO TIPO,
	CARGOVAGA.DESCRICAO CARGO_VAGA,
	CARGO.DESCRICAO CARGO,
	ESCALATRABALHO.SIGLA ESCALA,
	ALOCACAO.DESCRICAO JORNADA,
	FUNCIONARIO.DTADMISSAOORIGINAL DTADMISSAO,
	ALOCACAOMAODEOBRA.DTINICIO DTIMPLANTACAO,
	ALOCACAOMAODEOBRA.DTFIM DTENCERRAMENTO,
	MOTMOVIMENTACAO.DESCRICAO MOTIVO,
	ENTUSUARIO.NOMERESUMIDO  USUARIO,
	CAST(NULL AS VARCHAR(60)) AREALOCALSERVICO,
	ENTAREA.NOMECOMPLETO AREASUPERVISAO,
	CASE SITMOBRAHOJE.SITMOBRAHOJE
		WHEN 1 THEN 'EFETIVO'
		ELSE SITMOBRAHOJE.DESCRICAO
	END SITMOBRAHOJE,
	PLANOOPER.NOME as NOMEPLANOOPER
		FROM   ALOCACAOMAODEOBRA
			INNER JOIN SITMOBRAHOJE ON (ALOCACAOMAODEOBRA.TPCOBERTURA=SITMOBRAHOJE.SITMOBRAHOJE)
			INNER JOIN VAGAITEMCONTRATO ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=ALOCACAOMAODEOBRA.VAGAITEMCONTRATO
												AND ALOCACAOMAODEOBRA.DTINICIO <= CAST(GETDATE() AS DATE)
												AND (ALOCACAOMAODEOBRA.DTFIM >= CAST(GETDATE() AS DATE)
												OR ALOCACAOMAODEOBRA.DTFIM IS NULL))
			INNER JOIN CARGO CARGOVAGA ON (CARGOVAGA.CARGO=VAGAITEMCONTRATO.CARGO)
			inner join LIGAVGITEMCONTRATO ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=LIGAVGITEMCONTRATO.VAGAITEMCONTRATO
											AND LIGAVGITEMCONTRATO.DTIMPLANTACAO<= CAST(GETDATE() AS DATE)
											AND (LIGAVGITEMCONTRATO.DTENCERRAMENTO >= CAST(GETDATE() AS DATE)
											OR LIGAVGITEMCONTRATO.DTENCERRAMENTO IS NULL))
			inner join COMPOSICAOITENSCONTRATO on (LIGAVGITEMCONTRATO.COMPOSICAOITENSCONTRATO=COMPOSICAOITENSCONTRATO.COMPOSICAOITENSCONTRATO)
			inner join PLANO PLANOOPER on (COMPOSICAOITENSCONTRATO.PLANOREMOPER=PLANOOPER.PLANO)
			inner join ORIGEMVAGA ON (VAGAITEMCONTRATO.ORIGEMVAGA=ORIGEMVAGA.ORIGEMVAGA)
			inner join FUNCIONARIO ON (ALOCACAOMAODEOBRA.COLABORADOR=FUNCIONARIO.FUNCIONARIO)
			INNER JOIN RELACAOENTIDADE RELFUNC ON (FUNCIONARIO.FUNCIONARIO=RELFUNC.RELACAOENTIDADE and RELFUNC.SITUACAO=1)
			INNER JOIN ENTIDADE ENTFUNC ON (RELFUNC.PAPEL1=ENTFUNC.ENTIDADE)
			INNER JOIN TURNOTRABALHO ON (VAGAITEMCONTRATO.TURNOTRABALHO=TURNOTRABALHO.TURNOTRABALHO)
			INNER JOIN CARGOFUNCIONARIOS ON (FUNCIONARIO.FUNCIONARIO=CARGOFUNCIONARIOS.FUNCIONARIO
									AND CARGOFUNCIONARIOS.DTINICIO<=CAST(GETDATE() AS DATE)
									AND (CARGOFUNCIONARIOS.DTFIM >= CAST(GETDATE() AS DATE)
										OR CARGOFUNCIONARIOS.DTFIM IS NULL))
			INNER JOIN CARGO ON (CARGOFUNCIONARIOS.CARGO=CARGO.CARGO AND CARGO.SITUACAO=1)
			INNER JOIN RELACAOENTIDADE RELUSUARIO ON (ALOCACAOMAODEOBRA.USUARIOIMPLANTACAO=RELUSUARIO.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTUSUARIO ON (RELUSUARIO.PAPEL1=ENTUSUARIO.ENTIDADE)
			INNER JOIN ESCALATRABALHO ON (ESCALATRABALHO.ESCALATRABALHO=VAGAITEMCONTRATO.ESCALATRABALHO)
			INNER JOIN LIGAVGHORARIOOP ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=LIGAVGHORARIOOP.VAGAITEMCONTRATO
												AND LIGAVGHORARIOOP.DTIMPLANTACAO<=CAST(GETDATE() AS DATE)
												AND (LIGAVGHORARIOOP.DTENCERRAMENTO>=CAST(GETDATE() AS DATE)
													OR LIGAVGHORARIOOP.DTENCERRAMENTO IS NULL))
			INNER JOIN ALOCACAO ON (LIGAVGHORARIOOP.ALOCACAO=ALOCACAO.ALOCACAO)
			INNER JOIN MOTMOVIMENTACAO ON (ALOCACAOMAODEOBRA.MOTIVOIMPLANTACAO=MOTMOVIMENTACAO.MOTMOVIMENTACAO)
			INNER JOIN POSTOLOCALSERVICO ON (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO)
			INNER JOIN LOCALSERVICOEMP ON (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)
			INNER JOIN RELACAOENTIDADE RELEMPRESA ON (RELEMPRESA.RELACAOENTIDADE=VAGAITEMCONTRATO.EMPRESA AND RELEMPRESA.SITUACAO=1)
			INNER JOIN ENTIDADE ENTEMPRESA ON (RELEMPRESA.PAPEL1=ENTEMPRESA.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELLOCAL ON (RELLOCAL.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)
			INNER JOIN ENTIDADE ENTLOCAL ON (RELLOCAL.PAPEL1=ENTLOCAL.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELBASEOP ON (RELBASEOP.RELACAOENTIDADE=VAGAITEMCONTRATO.BASEOPERACIONAL)
			INNER JOIN ENTIDADE ENTBASEOP ON (RELBASEOP.PAPEL1=ENTBASEOP.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELCLIENTE ON (RELCLIENTE.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)
			INNER JOIN ENTIDADE ENTCLIENTE ON (RELCLIENTE.PAPEL1=ENTCLIENTE.ENTIDADE)
			INNER JOIN CLIENTE TABCLIENTE ON (TABCLIENTE.CLIENTE = RELCLIENTE.RELACAOENTIDADE)
			left join LIGAPOSTOLOCALAREASUPER
			left join RELACAOENTIDADE RELAREA on (RELAREA.RELACAOENTIDADE =  LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)
			left join ENTIDADE ENTAREA	on (ENTAREA.ENTIDADE = RELAREA.PAPEL1)
										on (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=VAGAITEMCONTRATO.POSTOLOCALSERVICO
											and LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO
											and LIGAPOSTOLOCALAREASUPER.SITUACAO=1)
					WHERE
						VAGAITEMCONTRATO.TPVAGA=1
						AND ALOCACAOMAODEOBRA.SITALOCACAO=1
						AND ENTCLIENTE.NOMERESUMIDO = 'RESERVA TÉCNICA'
						AND ENTLOCAL.NOMERESUMIDO NOT IN ('RESERVA - PC', 'RESERVA - PELLEGRINA - CAMPINAS',
															'RESERVA - PELLEGRINA - SÃO PAULO', 'RESERVA PROCESSO CRIMINAL',
																'RESERVAS - TRATATIVAS')
						ORDER BY
							ENTEMPRESA.NOMERESUMIDO,
							ENTBASEOP.NOMECOMPLETO,
							ENTCLIENTE.NOMERESUMIDO,
							ENTLOCAL.NOMECOMPLETO,
							ENTAREA.NOMECOMPLETO,
							RELFUNC.CODIGO;