SELECT   
	RELFUNCIONARIO.CODIGO AS RE, 
	ENTFUNCIONARIO.NOMECOMPLETO as NOMEFUNCIONARIO,  
	CARGOFUNCIONARIOS.CARGO,  
	CARGO.DESCRICAO AS DESC_CARGO,  
	FUNCIONARIO.DTADMISSAO, 
	FUNCIONARIO.DTDEMISSAO,  
	FUNCIONARIO.DTPRIMEIROPERIODOEXPERIENCIA,  
	FUNCIONARIO.DTSEGUNDOPERIODOEXPERIENCIA,  
	CASE    
		WHEN ((FUNCIONARIO.DTPRIMEIROPERIODOEXPERIENCIA >= FUNCIONARIO.DTDEMISSAO) OR (FUNCIONARIO.DTSEGUNDOPERIODOEXPERIENCIA >= FUNCIONARIO.DTDEMISSAO)) THEN 'SIM'    
		ELSE 'NÃO'   
	END AS EXPERIENCIA,   
	FUNCIONARIO.MOTIVODEMISSAO, 
	MOTMOVIMENTACAO.DESCRICAO AS DESC_MOTIVODEMISSAO, 
	RELEMPRESA.CODIGO AS COD_EMPRESA, 
	ENTEMPRESA.NOMERESUMIDO AS EMPRESA, 
	VAGAITEMCONTRATO.VINCULO AS COD_VINCULO,  
	CASE CARGO.VINCULO    
		WHEN 1 THEN 'OPERACIONAL'   
		WHEN 2 THEN 'ADMINISTRATIVO'   
		ELSE ''   
	END AS VINCULO, 
	LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO AS CODAREASUPERVISAO,  
	ENTAREA.NOMERESUMIDO  AS AREASUPERVISAO,  
	RELSUP.CODIGO AS COD_GESTOR, 
	CAUSARESCISAO.DESCRICAO CAUSARESCISAO, 
	CASE    
		WHEN SOLICITADESLIGAMENTO IS NOT NULL THEN 'SOLICITACAO'   
		ELSE 'MOVIMENTAÇÃO'  
	END AS TPDESLIGA, 
	SOLICITADESLIGAMENTO.OBSDESLIGAMENTO
		FROM   ENTIDADE ENTFUNCIONARIO  
		INNER JOIN RELACAOENTIDADE RELFUNCIONARIO ON (RELFUNCIONARIO.PAPEL1=ENTFUNCIONARIO.ENTIDADE 
															AND RELFUNCIONARIO.RELACAO=6)  
		INNER JOIN FUNCIONARIO ON (RELFUNCIONARIO.RELACAOENTIDADE = FUNCIONARIO.FUNCIONARIO         
															AND FUNCIONARIO.DTDEMISSAO IS NOT NULL)  
		INNER JOIN CARGOFUNCIONARIOS ON (FUNCIONARIO.FUNCIONARIO = CARGOFUNCIONARIOS.FUNCIONARIO        
															AND CARGOFUNCIONARIOS.DTINICIO<=FUNCIONARIO.DTDEMISSAO       
															AND (CARGOFUNCIONARIOS.DTFIM IS NULL 
															OR CARGOFUNCIONARIOS.DTFIM >= FUNCIONARIO.DTDEMISSAO))  
		INNER JOIN CARGO ON (CARGOFUNCIONARIOS.CARGO = CARGO.CARGO)  
		LEFT JOIN ALOCACAOMAODEOBRA               
		INNER JOIN VAGAITEMCONTRATO ON (VAGAITEMCONTRATO.VAGAITEMCONTRATO=ALOCACAOMAODEOBRA.VAGAITEMCONTRATO )              
		INNER JOIN POSTOLOCALSERVICO ON (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO)              
		INNER JOIN LOCALSERVICOEMP ON (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)          
		LEFT JOIN RELACAOENTIDADE RELSUP    
		INNER JOIN ENTIDADE ENTSUP ON (RELSUP.PAPEL1=ENTSUP.ENTIDADE) ON (RELSUP.RELACAOENTIDADE = LOCALSERVICOEMP.GESTOROPERACIONAL)           
		LEFT JOIN LIGAPOSTOLOCALAREASUPER                 
		INNER JOIN RELACAOENTIDADE RELAREA on (RELAREA.RELACAOENTIDADE =  LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO)         
		INNER JOIN ENTIDADE ENTAREA on (ENTAREA.ENTIDADE = RELAREA.PAPEL1) 
									ON (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO 
										AND LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO 
										and LIGAPOSTOLOCALAREASUPER.SITUACAO=1) 
									ON (ALOCACAOMAODEOBRA.COLABORADOR=RELFUNCIONARIO.RELACAOENTIDADE        
										AND ALOCACAOMAODEOBRA.TPALOCACAO=1       
										AND ALOCACAOMAODEOBRA.SITALOCACAO=1        
										AND ALOCACAOMAODEOBRA.DTINICIO<=FUNCIONARIO.DTDEMISSAO  
										AND ALOCACAOMAODEOBRA.DTFIM >= FUNCIONARIO.DTDEMISSAO)           
		INNER JOIN MOTMOVIMENTACAO ON (FUNCIONARIO.MOTIVODEMISSAO = MOTMOVIMENTACAO.MOTMOVIMENTACAO)           
		INNER JOIN RELACAOENTIDADE RELEMPRESA ON (RELEMPRESA.RELACAOENTIDADE = FUNCIONARIO.EMPRESA)        
		INNER JOIN ENTIDADE ENTEMPRESA ON (ENTEMPRESA.ENTIDADE = RELEMPRESA.PAPEL1)  
		LEFT JOIN DOMINIO CAUSARESCISAO ON (CAUSARESCISAO.CHAVE=FUNCIONARIO.CAUSARESCISAO AND CAUSARESCISAO.TIPODOMINIO=268)
		LEFT JOIN  SOLICITADESLIGAMENTO    
		INNER JOIN ESTADORELACAO ON (SOLICITADESLIGAMENTO.SOLICITADESLIGAMENTO=ESTADORELACAO.RELACAOENTIDADE   
											AND ESTADORELACAO.SITUACAO=1   
											AND ESTADORELACAO.DIAGRAMAESTADO=1607)  
								ON (SOLICITADESLIGAMENTO.SOLICITADESLIGAMENTO IN    
								(SELECT MAX(SOLICITADESLIGAMENTO) 
									FROM SOLICITADESLIGAMENTO  
										WHERE SOLICITADESLIGAMENTO.COLABORADOR=FUNCIONARIO.FUNCIONARIO))  
			WHERE  
				RELFUNCIONARIO.SITUACAO=1 
					ORDER BY  
					ENTEMPRESA.NOMERESUMIDO,  
					VAGAITEMCONTRATO.VINCULO, 
					ENTFUNCIONARIO.NOMECOMPLETO