SELECT
	ENTEMP.NOMERESUMIDO AS EMPRESA,
	CASE VAGAITEMCONTRATO.VINCULO
		WHEN 2 THEN 'ADMINISTRATIVO'
		ELSE 'OPERACIONAL'
	END VINCULO,
	RELENTFUNC.CODIGO RE,
	ENTFUNC.NOMERESUMIDO NOME,
	HISTDISCIPLINAR.HISTDISCIPLINAR,
	(SELECT  COUNT(ALOCHISTDISC.ALOCHISTDISC)
		FROM  ALOCHISTDISC
			INNER JOIN ALOCACAOMAODEOBRA ON (ALOCHISTDISC.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA AND ALOCACAOMAODEOBRA.SITALOCACAO=1)
			WHERE  ALOCHISTDISC.HISTDISCIPLINAR=HISTDISCIPLINAR.HISTDISCIPLINAR)
	QTD_VAGAS_DISCIPLINA,
	CASE
		WHEN ALOCACAOMAODEOBRA.TPCOBERTURA=1 THEN 'EFETIVO'
		ELSE TPCOBERTURA.DESCRICAO
	END TPCOBERTURA,
	VAGAITEMCONTRATO.VAGAITEMCONTRATO,
	OCORRENCIADISCIPLINA.DESCRICAO,
	CASE
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('FALTA ABONADA',
												'LICENÇA PATERNIDADE',
												'OBITO FAMILIAR',
												'LICENÇA MATRIMONIAL',
												'PODER JUDICIARIO',
												'LICENÇA MATERNIDADE',
												'DOAÇÃO DE SANGUE',
												'GESTANTE')			THEN 'Falta Abo.'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO = 'FALTA JUSTIFICADA'				THEN 'Falta Just.'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('SAÍDA ANTECIPADA JUSTIFICADA',
												'SAÍDA ANTECIPADA ABONADA')		THEN 'Saida Ant.'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO = 'RECICLAGEM POR OUTRA EMPRESA'	THEN 'Reciclagem por outra empresa'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('ATRASO JUSTIFICADO', 'ATRASO ABONADO')		THEN 'Atraso'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('FALTA INJUSTIFICADA - CEOPI',
												'AFASTAMENTO POR DOENÇA',
												'ADVERTÊNCIA ESCRITA',
												'SUSPENSÃO',
												'SAÍDA ANTECIPADA INJUSTIFICADA',
												'ATRASO INJUSTIFICADO')			THEN 'Outros'
		ELSE NUll
	END 'TipoDoc',
	HISTDISCIPLINAR.DTINICIOOCORRENCIA,
	HISTDISCIPLINAR.DTFIMOCORRENCIA,
	ESTADOWF.NOME FASEATUAL,
	CASE
		WHEN ESTADOWF.NOME = 'CONCLUÍDO' THEN 'CONCLUÍDO'
		WHEN ESTADOWF.NOME IN ('APROVAÇÃO', 'ELABORAÇÃO') THEN 'APROVAÇÃO'
		WHEN ESTADOWF.NOME = 'SARAPP' THEN 'PENDENTE'
		ELSE NULL
	END FASEFANTASIA,
	ENTCLI.NOMERESUMIDO CLIENTE,
	ENTCLI.NOMECOMPLETO CLIENTE_RAZAOSOCIAL,
	ENTLOCAL.NOMERESUMIDO LOCAL,
	ENTLOCAL.NOMECOMPLETO LOCAL_RAZAOSOCIAL,
	POLITICAPUNICAO.DESCRICAO AS PUNICAO,
	case
		WHEN ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA IS NOT NULL AND ALOCACAOMAODEOBRA.DTINICIO>=HISTDISCIPLINAR.DTINICIOOCORRENCIA THEN ALOCACAOMAODEOBRA.DTINICIO
		ELSE HISTDISCIPLINAR.DTINICIOOCORRENCIA
	end INICIALOC,
	case
		WHEN ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA IS NOT NULL and ALOCACAOMAODEOBRA.DTFIM<=HISTDISCIPLINAR.DTFIMOCORRENCIA THEN ALOCACAOMAODEOBRA.DTFIM
		ELSE HISTDISCIPLINAR.DTFIMOCORRENCIA
	end FIMALOC,
	HISTDISCIPLINAR.DTINICIO AS 'DTLançamento',
	HISTDISCIPLINAR.DTFIMAFASTAMENTO,
	UPPER(DOMINIOABONO.DESCRICAO) TPABONO,
	HISTDISCIPLINAR.RELACAOLOCALATENDIMENTO,
	ENTLOCALATEND.NOMERESUMIDO LOCALATENDIMENTO,
	MEDICO.CODREGMEDDENTISTA CRM,
	ENTMEDICO.NOMECOMPLETO MEDICO,
	HISTDISCIPLINAR.CID,
	LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(MAX), HISTDISCIPLINAR.OBSDOCUMENTO), CHAR(13),''), CHAR(10),''),CHAR(9),''),'',''))) OBSDOCUMENTO,
	CONVERT(VARCHAR(300),'') OBSDOCUMENTO_CONTINUACAO,
	LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(MAX), HISTDISCIPLINAR.OBSREQUISITANTE), CHAR(13),''), CHAR(10),''),CHAR(9),''),'',''))) OBSREQUISITANTE,
	CASE RESTRICAOCOBERTURA.TPRESTRICAO
		WHEN 1 THEN 'CLIENTE/LOCAL'
		WHEN 2 THEN 'LOCAL'
	END AS TPRESTRICAO,
	CASE MEDICO.TPMEDICO
		WHEN 1 THEN 'CRM'
		WHEN 2 THEN 'CRO'
		ELSE ''
	END TPDESMED
	FROM   RELACAOENTIDADE RELENTFUNC
		INNER JOIN ENTIDADE ENTFUNC ON (ENTFUNC.ENTIDADE = RELENTFUNC.PAPEL1)
		INNER JOIN FUNCIONARIO FUNCIONARIODIRETO ON (FUNCIONARIODIRETO.FUNCIONARIO=RELENTFUNC.RELACAOENTIDADE)
		INNER JOIN FUNCIONARIO FUNCIONARIOORIGINAL ON (FUNCIONARIOORIGINAL.FUNCORIGINAL=FUNCIONARIODIRETO.FUNCORIGINAL
														AND FUNCIONARIOORIGINAL.DTADMISSAO<=FUNCIONARIODIRETO.DTADMISSAO)
		INNER JOIN HISTDISCIPLINAR ON (HISTDISCIPLINAR.COLABORADOR=FUNCIONARIOORIGINAL.FUNCIONARIO
									and HISTDISCIPLINAR.SITUACAO=1)
		LEFT JOIN ESTADORELACAO
		INNER JOIN DIAGRAMAESTADO ON (DIAGRAMAESTADO.DIAGRAMAESTADO=ESTADORELACAO.DIAGRAMAESTADO)
		INNER JOIN ESTADOWF ON (ESTADOWF.ESTADOWF=DIAGRAMAESTADO.ESTADOWF)
							on (ESTADORELACAO.RELACAOENTIDADE=HISTDISCIPLINAR.HISTDISCIPLINAR
								AND ESTADORELACAO.SITUACAO=1)
		INNER JOIN OCORRENCIADISCIPLINA ON (OCORRENCIADISCIPLINA.OCORRENCIADISCIPLINA=HISTDISCIPLINAR.OCORRENCIADISCIPLINA
											AND HISTDISCIPLINAR.SITUACAO=1) ---------------------------------------------------
		LEFT JOIN DOMINIO DOMINIOABONO ON (DOMINIOABONO.TIPODOMINIO=172
										AND DOMINIOABONO.CHAVE=OCORRENCIADISCIPLINA.TPABONO)
		LEFT JOIN POLITICAPUNICAO ON (HISTDISCIPLINAR.POLITICAPUNICAO=POLITICAPUNICAO.POLITICAPUNICAO)
		left JOIN ALOCHISTDISC
		INNER JOIN ALOCACAOMAODEOBRA ON (ALOCHISTDISC.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA
											AND ALOCACAOMAODEOBRA.SITALOCACAO=1)
		INNER JOIN SITMOBRAHOJE TPCOBERTURA on (TPCOBERTURA.SITMOBRAHOJE=ALOCACAOMAODEOBRA.TPCOBERTURA)
		INNER JOIN VAGAITEMCONTRATO ON (ALOCACAOMAODEOBRA.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)
		INNER JOIN POSTOLOCALSERVICO ON (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO)
		INNER JOIN LOCALSERVICOEMP ON (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)
		INNER JOIN RELACAOENTIDADE RELENTPOSTO ON (RELENTPOSTO.RELACAOENTIDADE=POSTOLOCALSERVICO.POSTOSERVICO)
		INNER JOIN RELACAOENTIDADE RELENTLOCAL ON (RELENTLOCAL.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)
		INNER JOIN ENTIDADE ENTLOCAL ON (ENTLOCAL.ENTIDADE=RELENTLOCAL.PAPEL1)
		INNER JOIN RELACAOENTIDADE RELENTCLI on (RELENTCLI.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)
		INNER JOIN ENTIDADE ENTCLI	ON (ENTCLI.ENTIDADE=RELENTCLI.PAPEL1)
									ON (HISTDISCIPLINAR.HISTDISCIPLINAR=ALOCHISTDISC.HISTDISCIPLINAR)
		INNER JOIN RELACAOENTIDADE RELEMP on (RELEMP.RELACAOENTIDADE=FUNCIONARIODIRETO.EMPRESA)
		INNER JOIN ENTIDADE ENTEMP ON (ENTEMP.ENTIDADE=RELEMP.PAPEL1)
		LEFT JOIN RELACAOENTIDADE RELENTMEDICO
		INNER JOIN ENTIDADE ENTMEDICO ON (RELENTMEDICO.PAPEL1 = ENTMEDICO.ENTIDADE)
		INNER JOIN MEDICO	ON (RELENTMEDICO.RELACAOENTIDADE=MEDICO.MEDICO)
							ON (HISTDISCIPLINAR.MEDICO = RELENTMEDICO.RELACAOENTIDADE
								AND RELENTMEDICO.RELACAO = 501)
		LEFT JOIN RELACAOENTIDADE RELLOCALATEND
		INNER JOIN ENTIDADE ENTLOCALATEND ON (ENTLOCALATEND.ENTIDADE = RELLOCALATEND.PAPEL1)
											ON (RELLOCALATEND.RELACAOENTIDADE = HISTDISCIPLINAR.LOCALATENDIMENTO
												AND RELLOCALATEND.RELACAO = HISTDISCIPLINAR.RELACAOLOCALATENDIMENTO)
		LEFT JOIN RESTRICAOCOBERTURA ON (HISTDISCIPLINAR.HISTDISCIPLINAR = RESTRICAOCOBERTURA.HISTDISCIPLINAR)
		LEFT JOIN LIGAPOSTOLOCALAREASUPER ON (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO
											AND LIGAPOSTOLOCALAREASUPER.SITUACAO=1
											AND LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO)
		WHERE
			EXISTS (SELECT ESTADORELACAO
						FROM ESTADORELACAO
							WHERE ESTADORELACAO.RELACAOENTIDADE=HISTDISCIPLINAR.HISTDISCIPLINAR)
			and not exists (select ESTADORELACAO
								from ESTADORELACAO
									inner join DIAGRAMAESTADO  on DIAGRAMAESTADO.DIAGRAMAESTADO = ESTADORELACAO.DIAGRAMAESTADO
																	and DIAGRAMAESTADO.ESTADOWF in (307,308)
										where estadorelacao.RELACAOENTIDADE = HISTDISCIPLINAR.HISTDISCIPLINAR
												and ESTADORELACAO.SITUACAO=1)
			-- Filtra por DATA DE LANÇAMENTO (DTINICIO), igual ao slicer do BI.
			-- DATEADD inclui o dia final inteiro (DTINICIO tem hora).
			AND HISTDISCIPLINAR.DTINICIO >= @DATAINICIAL
			AND HISTDISCIPLINAR.DTINICIO < DATEADD(DAY, 1, @DATAFINAL)
			ORDER BY
				ENTEMP.NOMERESUMIDO,
				RELENTFUNC.CODIGO,
				HISTDISCIPLINAR.DTINICIOOCORRENCIA
