SELECT
	ENTEMP.NOMERESUMIDO AS EMPRESA,
	CASE VAGAITEMCONTRATO.VINCULO
		WHEN 2 THEN 'ADMINISTRATIVO'
		ELSE 'OPERACIONAL'
	END VINCULO,
	RELENTFUNC.CODIGO RE,
	ENTFUNC.NOMERESUMIDO NOME,
	HISTDISCIPLINAR.HISTDISCIPLINAR,
	(SELECT  COUNT(ALOCHISTDISC.ALOCHISTDISC)
		FROM ALOCHISTDISC WITH (NOLOCK) INNER JOIN ALOCACAOMAODEOBRA WITH (NOLOCK) ON (ALOCHISTDISC.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA AND ALOCACAOMAODEOBRA.SITALOCACAO=1)
			WHERE  ALOCHISTDISC.HISTDISCIPLINAR=HISTDISCIPLINAR.HISTDISCIPLINAR)
	QTD_VAGAS_DISCIPLINA,
	CASE
		WHEN ALOCACAOMAODEOBRA.TPCOBERTURA=1 THEN 'EFETIVO'
		ELSE TPCOBERTURA.DESCRICAO
	END TPCOBERTURA,
	VAGAITEMCONTRATO.VAGAITEMCONTRATO,
	OCORRENCIADISCIPLINA.DESCRICAO,
	CASE
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('FALTA ABONADA',
												'LICENÇA PATERNIDADE',
												'OBITO FAMILIAR',
												'LICENÇA MATRIMONIAL',
												'PODER JUDICIARIO',
												'LICENÇA MATERNIDADE',
												'DOAÇÃO DE SANGUE',
												'GESTANTE')			THEN 'Falta Abo.'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO = 'FALTA JUSTIFICADA'				THEN 'Falta Just.'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('SAÍDA ANTECIPADA JUSTIFICADA',
												'SAÍDA ANTECIPADA ABONADA')		THEN 'Saida Ant.'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO = 'RECICLAGEM POR OUTRA EMPRESA'	THEN 'Reciclagem por outra empresa'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('ATRASO JUSTIFICADO', 'ATRASO ABONADO')		THEN 'Atraso'
		WHEN OCORRENCIADISCIPLINA.DESCRICAO in ('FALTA INJUSTIFICADA - CEOPI',
												'AFASTAMENTO POR DOENÇA',
												'ADVERTÊNCIA ESCRITA',
												'SUSPENSÃO',
												'SAÍDA ANTECIPADA INJUSTIFICADA',
												'ATRASO INJUSTIFICADO')			THEN 'Outros'
		ELSE NUll
	END 'TipoDoc',
	HISTDISCIPLINAR.DTINICIOOCORRENCIA,
	HISTDISCIPLINAR.DTFIMOCORRENCIA,
	ESTADOWF.NOME FASEATUAL,
	CASE
		WHEN ESTADOWF.NOME = 'CONCLUÍDO' THEN 'CONCLUÍDO'
		WHEN ESTADOWF.NOME IN ('APROVAÇÃO', 'ELABORAÇÃO') THEN 'APROVAÇÃO'
		WHEN ESTADOWF.NOME = 'SARAPP' THEN 'PENDENTE'
		ELSE NULL
	END FASEFANTASIA,
	ENTCLI.NOMERESUMIDO CLIENTE,
	ENTCLI.NOMECOMPLETO CLIENTE_RAZAOSOCIAL,
	ENTLOCAL.NOMERESUMIDO LOCAL,
	ENTLOCAL.NOMECOMPLETO LOCAL_RAZAOSOCIAL,
	POLITICAPUNICAO.DESCRICAO AS PUNICAO,
	case
		WHEN ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA IS NOT NULL AND ALOCACAOMAODEOBRA.DTINICIO>=HISTDISCIPLINAR.DTINICIOOCORRENCIA THEN ALOCACAOMAODEOBRA.DTINICIO
		ELSE HISTDISCIPLINAR.DTINICIOOCORRENCIA
	end INICIALOC,
	case
		WHEN ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA IS NOT NULL and ALOCACAOMAODEOBRA.DTFIM<=HISTDISCIPLINAR.DTFIMOCORRENCIA THEN ALOCACAOMAODEOBRA.DTFIM
		ELSE HISTDISCIPLINAR.DTFIMOCORRENCIA
	end FIMALOC,
	HISTDISCIPLINAR.DTINICIO AS 'DTLançamento',
	HISTDISCIPLINAR.DTFIMAFASTAMENTO,
	UPPER(DOMINIOABONO.DESCRICAO) TPABONO,
	HISTDISCIPLINAR.RELACAOLOCALATENDIMENTO,
	ENTLOCALATEND.NOMERESUMIDO LOCALATENDIMENTO,
	MEDICO.CODREGMEDDENTISTA CRM,
	ENTMEDICO.NOMECOMPLETO MEDICO,
	HISTDISCIPLINAR.CID,
	LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(MAX), HISTDISCIPLINAR.OBSDOCUMENTO), CHAR(13),''), CHAR(10),''),CHAR(9),''),'',''))) OBSDOCUMENTO,
	CONVERT(VARCHAR(300),'') OBSDOCUMENTO_CONTINUACAO,
	LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(MAX), HISTDISCIPLINAR.OBSREQUISITANTE), CHAR(13),''), CHAR(10),''),CHAR(9),''),'',''))) OBSREQUISITANTE,
	CASE RESTRICAOCOBERTURA.TPRESTRICAO
		WHEN 1 THEN 'CLIENTE/LOCAL'
		WHEN 2 THEN 'LOCAL'
	END AS TPRESTRICAO,
	CASE MEDICO.TPMEDICO
		WHEN 1 THEN 'CRM'
		WHEN 2 THEN 'CRO'
		ELSE ''
	END TPDESMED
	FROM RELACAOENTIDADE RELENTFUNC WITH (NOLOCK)
		INNER JOIN ENTIDADE ENTFUNC WITH (NOLOCK) ON (ENTFUNC.ENTIDADE = RELENTFUNC.PAPEL1)
		INNER JOIN FUNCIONARIO FUNCIONARIODIRETO WITH (NOLOCK) ON (FUNCIONARIODIRETO.FUNCIONARIO=RELENTFUNC.RELACAOENTIDADE)
		INNER JOIN FUNCIONARIO FUNCIONARIOORIGINAL WITH (NOLOCK) ON (FUNCIONARIOORIGINAL.FUNCORIGINAL=FUNCIONARIODIRETO.FUNCORIGINAL
														AND FUNCIONARIOORIGINAL.DTADMISSAO<=FUNCIONARIODIRETO.DTADMISSAO)
		INNER JOIN HISTDISCIPLINAR WITH (NOLOCK) ON (HISTDISCIPLINAR.COLABORADOR=FUNCIONARIOORIGINAL.FUNCIONARIO
									and HISTDISCIPLINAR.SITUACAO=1)
		LEFT JOIN ESTADORELACAO WITH (NOLOCK) INNER JOIN DIAGRAMAESTADO WITH (NOLOCK) ON (DIAGRAMAESTADO.DIAGRAMAESTADO=ESTADORELACAO.DIAGRAMAESTADO)
		INNER JOIN ESTADOWF WITH (NOLOCK) ON (ESTADOWF.ESTADOWF=DIAGRAMAESTADO.ESTADOWF)
							on (ESTADORELACAO.RELACAOENTIDADE=HISTDISCIPLINAR.HISTDISCIPLINAR
								AND ESTADORELACAO.SITUACAO=1)
		INNER JOIN OCORRENCIADISCIPLINA WITH (NOLOCK) ON (OCORRENCIADISCIPLINA.OCORRENCIADISCIPLINA=HISTDISCIPLINAR.OCORRENCIADISCIPLINA
											AND HISTDISCIPLINAR.SITUACAO=1) ---------------------------------------------------
		LEFT JOIN DOMINIO DOMINIOABONO WITH (NOLOCK) ON (DOMINIOABONO.TIPODOMINIO=172
										AND DOMINIOABONO.CHAVE=OCORRENCIADISCIPLINA.TPABONO)
		LEFT JOIN POLITICAPUNICAO WITH (NOLOCK) ON (HISTDISCIPLINAR.POLITICAPUNICAO=POLITICAPUNICAO.POLITICAPUNICAO)
		left JOIN ALOCHISTDISC WITH (NOLOCK) INNER JOIN ALOCACAOMAODEOBRA WITH (NOLOCK) ON (ALOCHISTDISC.ALOCACAOMAODEOBRA=ALOCACAOMAODEOBRA.ALOCACAOMAODEOBRA
											AND ALOCACAOMAODEOBRA.SITALOCACAO=1)
		INNER JOIN SITMOBRAHOJE TPCOBERTURA WITH (NOLOCK) on (TPCOBERTURA.SITMOBRAHOJE=ALOCACAOMAODEOBRA.TPCOBERTURA)
		INNER JOIN VAGAITEMCONTRATO WITH (NOLOCK) ON (ALOCACAOMAODEOBRA.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)
		INNER JOIN POSTOLOCALSERVICO WITH (NOLOCK) ON (VAGAITEMCONTRATO.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO)
		INNER JOIN LOCALSERVICOEMP WITH (NOLOCK) ON (POSTOLOCALSERVICO.LOCALSERVICOEMP=LOCALSERVICOEMP.LOCALSERVICOEMP)
		INNER JOIN RELACAOENTIDADE RELENTPOSTO WITH (NOLOCK) ON (RELENTPOSTO.RELACAOENTIDADE=POSTOLOCALSERVICO.POSTOSERVICO)
		INNER JOIN RELACAOENTIDADE RELENTLOCAL WITH (NOLOCK) ON (RELENTLOCAL.RELACAOENTIDADE=VAGAITEMCONTRATO.LOCALSERVICO)
		INNER JOIN ENTIDADE ENTLOCAL WITH (NOLOCK) ON (ENTLOCAL.ENTIDADE=RELENTLOCAL.PAPEL1)
		INNER JOIN RELACAOENTIDADE RELENTCLI WITH (NOLOCK) on (RELENTCLI.RELACAOENTIDADE=VAGAITEMCONTRATO.CLIENTE)
		INNER JOIN ENTIDADE ENTCLI WITH (NOLOCK)	ON (ENTCLI.ENTIDADE=RELENTCLI.PAPEL1)
									ON (HISTDISCIPLINAR.HISTDISCIPLINAR=ALOCHISTDISC.HISTDISCIPLINAR)
		INNER JOIN RELACAOENTIDADE RELEMP WITH (NOLOCK) on (RELEMP.RELACAOENTIDADE=FUNCIONARIODIRETO.EMPRESA)
		INNER JOIN ENTIDADE ENTEMP WITH (NOLOCK) ON (ENTEMP.ENTIDADE=RELEMP.PAPEL1)
		LEFT JOIN RELACAOENTIDADE RELENTMEDICO WITH (NOLOCK)
		INNER JOIN ENTIDADE ENTMEDICO WITH (NOLOCK) ON (RELENTMEDICO.PAPEL1 = ENTMEDICO.ENTIDADE)
		INNER JOIN MEDICO WITH (NOLOCK) ON (RELENTMEDICO.RELACAOENTIDADE=MEDICO.MEDICO)
							ON (HISTDISCIPLINAR.MEDICO = RELENTMEDICO.RELACAOENTIDADE
								AND RELENTMEDICO.RELACAO = 501)
		LEFT JOIN RELACAOENTIDADE RELLOCALATEND WITH (NOLOCK)
		INNER JOIN ENTIDADE ENTLOCALATEND WITH (NOLOCK) ON (ENTLOCALATEND.ENTIDADE = RELLOCALATEND.PAPEL1)
											ON (RELLOCALATEND.RELACAOENTIDADE = HISTDISCIPLINAR.LOCALATENDIMENTO
												AND RELLOCALATEND.RELACAO = HISTDISCIPLINAR.RELACAOLOCALATENDIMENTO)
		LEFT JOIN RESTRICAOCOBERTURA WITH (NOLOCK) ON (HISTDISCIPLINAR.HISTDISCIPLINAR = RESTRICAOCOBERTURA.HISTDISCIPLINAR)
		LEFT JOIN LIGAPOSTOLOCALAREASUPER WITH (NOLOCK) ON (LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO=POSTOLOCALSERVICO.POSTOLOCALSERVICO
											AND LIGAPOSTOLOCALAREASUPER.SITUACAO=1
											AND LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO=VAGAITEMCONTRATO.TURNOTRABALHO)
		WHERE
			EXISTS (SELECT ESTADORELACAO
						FROM ESTADORELACAO WITH (NOLOCK) WHERE ESTADORELACAO.RELACAOENTIDADE=HISTDISCIPLINAR.HISTDISCIPLINAR)
			and not exists (select ESTADORELACAO
								from ESTADORELACAO WITH (NOLOCK) inner join DIAGRAMAESTADO WITH (NOLOCK) on DIAGRAMAESTADO.DIAGRAMAESTADO = ESTADORELACAO.DIAGRAMAESTADO
																	and DIAGRAMAESTADO.ESTADOWF in (307,308)
										where estadorelacao.RELACAOENTIDADE = HISTDISCIPLINAR.HISTDISCIPLINAR
												and ESTADORELACAO.SITUACAO=1)
			-- Filtra por DATA DE LANÇAMENTO (DTINICIO), igual ao slicer do BI.
			-- DATEADD inclui o dia final inteiro (DTINICIO tem hora).
			AND HISTDISCIPLINAR.DTINICIO >= @DATAINICIAL
			AND HISTDISCIPLINAR.DTINICIO < DATEADD(DAY, 1, @DATAFINAL)
			ORDER BY
				ENTEMP.NOMERESUMIDO,
				RELENTFUNC.CODIGO,
				HISTDISCIPLINAR.DTINICIOOCORRENCIA
