-- Período parametrizado: @DATAINICIAL / @DATAFINAL (injetados pelo backend).
SELECT
	DADOS.TIPO,
	CASE DADOS.TIPO
		WHEN 1 THEN 'FALTA'
		WHEN 2 THEN 'ATRASO ENTRADA'
		WHEN 3 THEN 'ATRASO REFEIÇÃO'
		ELSE 'LIB. PARCIAL FUNCIONÁRIO'
	END AS TIPO_DESCRICAO,
	ENTEMP.NOMERESUMIDO AS EMPRESA,
	RELFUNC.CODIGO AS RE,
	ENTFUNC.NOMECOMPLETO AS NOME_FUNCIONARIO,
	DADOS.DATA,
	ISNULL(
		FORMAT(DATEADD(DAY, 16, DADOS.DATA), 'MM/yyyy'),
		'SEM DATA'
	) AS COMPETENCIA,
	TURNOTRABALHO.DESCRICAO AS TURNO,
	ESCALATRABALHO.DESCRICAO AS ESCALA,
	ENTCLI.NOMERESUMIDO AS NOME_CLIENTE,
	ENTLOC.NOMERESUMIDO AS NOME_LOCAL
	FROM	(SELECT    1 AS TIPO,
				PONTO.COLABORADOR,
				PONTO.VAGAITEMCONTRATO,
				PONTO.DATA
				FROM PONTO WITH (NOLOCK) WHERE PONTO.SITMOBRAHOJE=9
					AND PONTO.DATA BETWEEN @DATAINICIAL AND @DATAFINAL

				UNION ALL

			SELECT
				COMPLPONTO.TPMOVIMENTO,
				PONTO.COLABORADOR,
				PONTO.VAGAITEMCONTRATO,
				PONTO.DATA
				FROM PONTO WITH (NOLOCK) INNER JOIN COMPLPONTO WITH (NOLOCK) ON (PONTO.PONTO=COMPLPONTO.PONTO
												AND COMPLPONTO.SITUACAO=1
												AND COMPLPONTO.TPMOVIMENTO IN (2,4,8))
						WHERE 1=1
						AND PONTO.DATA BETWEEN @DATAINICIAL AND @DATAFINAL
						) DADOS
			INNER JOIN RELACAOENTIDADE RELFUNC WITH (NOLOCK) ON (DADOS.COLABORADOR=RELFUNC.RELACAOENTIDADE AND RELFUNC.SITUACAO=1)
			INNER JOIN RELACAOENTIDADE RELEMP WITH (NOLOCK) ON (RELFUNC.PAPEL2=RELEMP.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTEMP WITH (NOLOCK) ON (RELEMP.PAPEL1=ENTEMP.ENTIDADE)
			INNER JOIN ENTIDADE ENTFUNC WITH (NOLOCK) ON (RELFUNC.PAPEL1=ENTFUNC.ENTIDADE)
			INNER JOIN VAGAITEMCONTRATO WITH (NOLOCK) ON (DADOS.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)
			INNER JOIN ESCALATRABALHO WITH (NOLOCK) ON (VAGAITEMCONTRATO.ESCALATRABALHO=ESCALATRABALHO.ESCALATRABALHO)
			INNER JOIN RELACAOENTIDADE RELCLI WITH (NOLOCK) ON (VAGAITEMCONTRATO.CLIENTE=RELCLI.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTCLI WITH (NOLOCK) ON (RELCLI.PAPEL1=ENTCLI.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELLOC WITH (NOLOCK) ON (VAGAITEMCONTRATO.LOCALSERVICO=RELLOC.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTLOC WITH (NOLOCK) ON (RELLOC.PAPEL1=ENTLOC.ENTIDADE)
			INNER JOIN TURNOTRABALHO WITH (NOLOCK) ON (VAGAITEMCONTRATO.TURNOTRABALHO=TURNOTRABALHO.TURNOTRABALHO)
			LEFT JOIN HISTDISCIPLINAR WITH (NOLOCK) ON (DADOS.COLABORADOR=HISTDISCIPLINAR.COLABORADOR
											AND DADOS.DATA>=HISTDISCIPLINAR.DTINICIOOCORRENCIA
											AND DADOS.DATA<=HISTDISCIPLINAR.DTFIMOCORRENCIA)
				WHERE HISTDISCIPLINAR.HISTDISCIPLINAR IS NULL
					AND DADOS.TIPO = 1   -- só FALTA (remove Atraso Entrada/Refeição e Liberação Parcial)
					ORDER BY
						ENTEMP.NOMERESUMIDO,
						TIPO_DESCRICAO,
						RELFUNC.CODIGO,
						DADOS.DATA
