-- Período parametrizado: @DATAINICIAL / @DATAFINAL (injetados pelo backend).
SELECT
    DADOS.EMPRESACLIENTE,
    DADOS.NOMECLI,		
    DADOS.NOMELOCAL,  
    DADOS.DATAPONTO,
    DADOS.SITMOBRAHOJE,  
    DADOS.SITUACAOMOBRA, 
    DADOS.SITTRABALHO,   
    DADOS.PARAMETROGERAL, 
    DADOS.EMPRESAFUNC, 
    DADOS.RE, 
    DADOS.NOMEFUNC,  
    DADOS.ESCALA, 
    DADOS.CARGO, 
    DADOS.AREASUPER, 
    DADOS.STATUS_FALTA
FROM (
    SELECT   
        ENTEMPC.NOMERESUMIDO AS EMPRESACLIENTE,   
        ENTCLI.NOMERESUMIDO  AS NOMECLI,   
        ENTLOC.NOMERESUMIDO  AS NOMELOCAL,   
        PONTO.DATA           AS DATAPONTO,   
        PONTO.SITMOBRAHOJE,   
        PONTO.SITUACAOMOBRA,   
        PONTO.SITTRABALHO,   

        (SELECT TOP 1 
            CASE WHEN VALOR = 'Cw==' THEN 1 ELSE 0 END
         FROM PARAMETROS WITH (NOLOCK) WHERE PARAMETROS = 63) AS PARAMETROGERAL,   

        ENTEMP.NOMERESUMIDO AS EMPRESAFUNC,   
        RELFUN.CODIGO       AS RE,   
        ENTFUN.NOMERESUMIDO AS NOMEFUNC,   
        ESCALATRABALHO.DESCRICAO AS ESCALA,   
        CARGO.DESCRICAO     AS CARGO,   
        ENTARE.NOMERESUMIDO AS AREASUPER,   

        CASE 
            WHEN PONTO.SITUACAOMOBRA = 7 
                THEN 'SUSPENSÃO'
            WHEN PONTO.SITMOBRAHOJE = 9 AND PONTO.TPABONOPONTO = 3 
                THEN 'FALTA LEGAL'
            WHEN PONTO.SITMOBRAHOJE = 9 AND PONTO.TPABONOPONTO = 2 
                THEN 'FALTA ABONADA'
            WHEN PONTO.SITMOBRAHOJE = 9 AND PONTO.TPABONOPONTO = 4 
                THEN 'FALTA JUSTIFICADA'
            WHEN PONTO.SITMOBRAHOJE = 9 
                 AND COALESCE(PONTO.TPABONOPONTO,0) IN (0,1,5)
                THEN 'FALTA INJUSTIFICADA'
            ELSE 'SEM OCORRÊNCIA'
        END AS STATUS_FALTA

    FROM PONTO WITH (NOLOCK) INNER JOIN RELACAOENTIDADE RELFUN WITH (NOLOCK) ON (PONTO.COLABORADOR = RELFUN.RELACAOENTIDADE AND RELFUN.SITUACAO = 1)
        INNER JOIN ENTIDADE ENTFUN WITH (NOLOCK) ON (RELFUN.PAPEL1 = ENTFUN.ENTIDADE)
        INNER JOIN VAGAITEMCONTRATO WITH (NOLOCK) ON (PONTO.VAGAITEMCONTRATO = VAGAITEMCONTRATO.VAGAITEMCONTRATO)
        INNER JOIN CARGO WITH (NOLOCK) ON (VAGAITEMCONTRATO.CARGO = CARGO.CARGO)
        INNER JOIN RELACAOENTIDADE RELCLI WITH (NOLOCK) ON (VAGAITEMCONTRATO.CLIENTE = RELCLI.RELACAOENTIDADE)
        INNER JOIN ENTIDADE ENTCLI WITH (NOLOCK) ON (RELCLI.PAPEL1 = ENTCLI.ENTIDADE)
        INNER JOIN RELACAOENTIDADE RELLOC WITH (NOLOCK) ON (VAGAITEMCONTRATO.LOCALSERVICO = RELLOC.RELACAOENTIDADE)
        INNER JOIN ENTIDADE ENTLOC WITH (NOLOCK) ON (RELLOC.PAPEL1 = ENTLOC.ENTIDADE)
        INNER JOIN FUNCIONARIO WITH (NOLOCK) ON (PONTO.COLABORADOR = FUNCIONARIO.FUNCIONARIO)
        INNER JOIN RELACAOENTIDADE RELEMP WITH (NOLOCK) ON (FUNCIONARIO.EMPRESA = RELEMP.RELACAOENTIDADE)
        INNER JOIN ENTIDADE ENTEMP WITH (NOLOCK) ON (RELEMP.PAPEL1 = ENTEMP.ENTIDADE)
        INNER JOIN ESCALATRABALHO WITH (NOLOCK) ON (VAGAITEMCONTRATO.ESCALATRABALHO = ESCALATRABALHO.ESCALATRABALHO)
        INNER JOIN RELACAOENTIDADE RELEMPC WITH (NOLOCK) ON (VAGAITEMCONTRATO.EMPRESA = RELEMPC.RELACAOENTIDADE)
        INNER JOIN ENTIDADE ENTEMPC WITH (NOLOCK) ON (RELEMPC.PAPEL1 = ENTEMPC.ENTIDADE)
        LEFT JOIN LIGAPOSTOLOCALAREASUPER WITH (NOLOCK) ON (
            VAGAITEMCONTRATO.POSTOLOCALSERVICO = LIGAPOSTOLOCALAREASUPER.POSTOLOCALSERVICO
            AND VAGAITEMCONTRATO.TURNOTRABALHO = LIGAPOSTOLOCALAREASUPER.TURNOTRABALHO
            AND LIGAPOSTOLOCALAREASUPER.SITUACAO = 1
        )
        LEFT JOIN RELACAOENTIDADE RELARE WITH (NOLOCK) ON (LIGAPOSTOLOCALAREASUPER.AREASUPERVISAO = RELARE.RELACAOENTIDADE)
        LEFT JOIN ENTIDADE ENTARE WITH (NOLOCK) ON (RELARE.PAPEL1 = ENTARE.ENTIDADE)

    WHERE (PONTO.SITMOBRAHOJE = 9 OR PONTO.SITUACAOMOBRA = 7)
        -- Locais de Abandono/Afastamento/Faltante são ocultados na tela (toggle),
        -- não mais filtrados aqui, para a regra ser unificada entre os relatórios.
) DADOS
WHERE 
    DADOS.DATAPONTO BETWEEN @DATAINICIAL AND @DATAFINAL
    AND (
        (DADOS.SITMOBRAHOJE = 9 AND DADOS.SITTRABALHO = 1)
        OR (DADOS.PARAMETROGERAL = 0 AND DADOS.SITUACAOMOBRA = 7 AND DADOS.SITTRABALHO = 1)
        OR (DADOS.PARAMETROGERAL = 1 AND DADOS.SITUACAOMOBRA = 7 AND DADOS.SITTRABALHO >= 1)
    )

ORDER BY   
    DADOS.EMPRESACLIENTE,
    DADOS.NOMECLI, 
    DADOS.NOMELOCAL,  
    DADOS.DATAPONTO, 
    DADOS.EMPRESAFUNC, 
    DADOS.NOMEFUNC,  
    DADOS.RE;
