-- Período parametrizado: @DATAINICIAL / @DATAFINAL (injetados pelo backend).
SELECT
	DADOS.TIPO,
	CASE DADOS.TIPO
		WHEN 1 THEN 'FALTA'
		WHEN 2 THEN 'ATRASO ENTRADA'
		WHEN 3 THEN 'ATRASO REFEIÇÃO'
		ELSE 'LIB. PARCIAL FUNCIONÁRIO'
	END AS TIPO_DESCRICAO,
	ENTEMP.NOMERESUMIDO AS EMPRESA,
	RELFUNC.CODIGO AS RE,
	ENTFUNC.NOMECOMPLETO AS NOME_FUNCIONARIO,
	DADOS.DATA,
	ISNULL(
		FORMAT(DATEADD(DAY, 16, DADOS.DATA), 'MM/yyyy'),
		'SEM DATA'
	) AS COMPETENCIA,
	TURNOTRABALHO.DESCRICAO AS TURNO,
	ESCALATRABALHO.DESCRICAO AS ESCALA,
	ENTCLI.NOMERESUMIDO AS NOME_CLIENTE,
	ENTLOC.NOMERESUMIDO AS NOME_LOCAL
	FROM	(SELECT    1 AS TIPO,
				PONTO.COLABORADOR,
				PONTO.VAGAITEMCONTRATO,
				PONTO.DATA
				FROM PONTO
					WHERE PONTO.SITMOBRAHOJE=9
					AND PONTO.DATA BETWEEN @DATAINICIAL AND @DATAFINAL

				UNION ALL

			SELECT
				COMPLPONTO.TPMOVIMENTO,
				PONTO.COLABORADOR,
				PONTO.VAGAITEMCONTRATO,
				PONTO.DATA
				FROM PONTO
					INNER JOIN COMPLPONTO ON (PONTO.PONTO=COMPLPONTO.PONTO
												AND COMPLPONTO.SITUACAO=1
												AND COMPLPONTO.TPMOVIMENTO IN (2,4,8))
						WHERE 1=1
						AND PONTO.DATA BETWEEN @DATAINICIAL AND @DATAFINAL
						) DADOS
			INNER JOIN RELACAOENTIDADE RELFUNC ON (DADOS.COLABORADOR=RELFUNC.RELACAOENTIDADE AND RELFUNC.SITUACAO=1)
			INNER JOIN RELACAOENTIDADE RELEMP ON (RELFUNC.PAPEL2=RELEMP.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTEMP ON (RELEMP.PAPEL1=ENTEMP.ENTIDADE)
			INNER JOIN ENTIDADE ENTFUNC ON (RELFUNC.PAPEL1=ENTFUNC.ENTIDADE)
			INNER JOIN VAGAITEMCONTRATO ON (DADOS.VAGAITEMCONTRATO=VAGAITEMCONTRATO.VAGAITEMCONTRATO)
			INNER JOIN ESCALATRABALHO ON (VAGAITEMCONTRATO.ESCALATRABALHO=ESCALATRABALHO.ESCALATRABALHO)
			INNER JOIN RELACAOENTIDADE RELCLI ON (VAGAITEMCONTRATO.CLIENTE=RELCLI.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTCLI ON (RELCLI.PAPEL1=ENTCLI.ENTIDADE)
			INNER JOIN RELACAOENTIDADE RELLOC ON (VAGAITEMCONTRATO.LOCALSERVICO=RELLOC.RELACAOENTIDADE)
			INNER JOIN ENTIDADE ENTLOC ON (RELLOC.PAPEL1=ENTLOC.ENTIDADE)
			INNER JOIN TURNOTRABALHO ON (VAGAITEMCONTRATO.TURNOTRABALHO=TURNOTRABALHO.TURNOTRABALHO)
			LEFT JOIN HISTDISCIPLINAR ON (DADOS.COLABORADOR=HISTDISCIPLINAR.COLABORADOR
											AND DADOS.DATA>=HISTDISCIPLINAR.DTINICIOOCORRENCIA
											AND DADOS.DATA<=HISTDISCIPLINAR.DTFIMOCORRENCIA)
				WHERE HISTDISCIPLINAR.HISTDISCIPLINAR IS NULL
					AND DADOS.TIPO = 1   -- só FALTA (remove Atraso Entrada/Refeição e Liberação Parcial)
					ORDER BY
						ENTEMP.NOMERESUMIDO,
						TIPO_DESCRICAO,
						RELFUNC.CODIGO,
						DADOS.DATA
